### ISSUE TITLE
Avoid hardcoded proxies / Promoted channels

### ISSUE THREAD

**Issue by 9seconds** [9seconds/mtg#1]
If we use Telegram API, we do not need to have all these hardcodes + now it is clear why do we need negative DCs

```console
$ curl -s https://core.telegram.org/getProxyConfig -H "Accept: text/plain" --compressed
```

Unfortunately usage of force probability is totally unclear because _this API call is not public_: https://core.telegram.org/methods

🤦‍♂️

**Comment by 9seconds** [comment]
Does anyone understand how to use secret from `getProxySecret`? I can't connect to proxies from `getProxiesConfig` without it.

**Comment by drdaeman** [comment]
The "official" proxy source is an ugliest mess I ever saw. Here's how far I got from the source:

The password file is actually read in [`aes_load_pwd_file`](https://github.com/TelegramMessenger/MTProxy/blob/cc7b7097a5bc1681d0f4c05d5f07576c8b279fc4/net/net-crypto-aes.c#L138). That function does some odd stuff unrelated to the key usage (like seeding `srand`, even though it doesn't use PRNG itself) but the secret is essentially stored in [`main_secret.secret`](https://github.com/TelegramMessenger/MTProxy/blob/cc7b7097a5bc1681d0f4c05d5f07576c8b279fc4/net/net-crypto-aes.c#L213). There's also an MD5 hash of the secret calculated and stored into `pwd_config_md5` but I don't see that it's used in any meaningful manner.

Long story short, the secret then [gets passed](https://github.com/TelegramMessenger/MTProxy/blob/cc7b7097a5bc1681d0f4c05d5f07576c8b279fc4/net/net-tcp-rpc-client.c#L675) (hopefully, intact) to `aes_create_keys` (a `secret` there is a reference to `main_secret`). There, they calculate keys in a quite weird manner. First, they lay down all the data (IPs, nonce, whenever it's a server or not, etc) in that `str` buffer. Then, they [XOR it with `temp_key`](https://github.com/TelegramMessenger/MTProxy/blob/cc7b7097a5bc1681d0f4c05d5f07576c8b279fc4/net/net-crypto-aes.c#L283). And then run [a bunch of `md5` and `sha1` transformations](https://github.com/TelegramMessenger/MTProxy/blob/cc7b7097a5bc1681d0f4c05d5f07576c8b279fc4/net/net-crypto-aes.c#L295) to derive two AES keys (first they derive a `write_key` then they swap "CLIENT" and "SERVER" to derive `read_key`).

The memory layout of `str` seems to be:

1. [0-15] 16 bytes - nonce for server
2. [16-31] 16 bytes - nonce for client
3. [32-35] 4 bytes - client timestamp (uh... 32-bit signed integer)
4. [36-39] 4 bytes - server IPv4 address, not sure what endianness
5. [40-41] 2 bytes - client port, 16-bit unsigned integer, also not sure about endianness
6. [42-47] 6 bytes - null-terminated string "CLIENT" or "SERVER"
7. [48-51] 4 bytes - client IPv4 address
8. [52-53] 2 bytes - server port, 16-bit unsigned integer
9. [54-?] Variable length - secret data read from file
10. Immediately followed by 16 bytes server nonce
11. Immediately followed by 16 bytes client nonce

Thus, total length is `86 + len(secret)`.

The `temp_key` they use to XOR is a blob, up to 256-bytes (only `strlen(str)` is used, of course) result of [`dh_third_round`](https://github.com/TelegramMessenger/MTProxy/blob/cc7b7097a5bc1681d0f4c05d5f07576c8b279fc4/net/net-crypto-dh.c#L224) which is called from [`tcp_rpcc_process_nonce_packet`](https://github.com/TelegramMessenger/MTProxy/blob/cc7b7097a5bc1681d0f4c05d5f07576c8b279fc4/net/net-tcp-rpc-client.c#L105). I'm at loss there. Also, if DH is not used then `temp_key` (called `temp_dh` there) is essentially uninitialized memory.

This is as far as I got for now, sorry.

It seems that there's way more to obfuscated2 than just AES-encrypted traffic with IV and keys attached. There seems to be Diffie-Hellman key exchange and there are some "extra keys" whatever it could mean.

**Comment by 9seconds** [comment]
Thanks a lot, man! Yep, I've followed the same trail and stopped at the same point (a little bit earlier to be fair). I see that another "handshake" is formed here but have no time to (oh my, I have to pronounce that) "reverse engineer" the sources further. It all just makes no sense.

Yep, for now we have ips of telegram with direct connectivity and we can use them. So, fortunately there is no any negative side effect of unusing these proxies from getProxyConfig.

Afaik, also nobody understands how to promote the channel for now :/

So, we have this issue: https://github.com/TelegramMessenger/MTProxy/issues/21 Let's hope that one day Telegram will explain how and what to do with that stuff

**Comment by alexbers** [comment]
I spent few days understanding the code and now I know how to promote channels. I added this functionality to my python mtproto proxy implementation: https://github.com/alexbers/mtprotoproxy/commit/fee5a0c05ae855d97e12a46253e4ad50395df17c 

Hope that code is slightly more readable than the code of official proxy.

**Comment by 9seconds** [comment]
For all those who interested in how it goes: unfortunately, on this week I had no chance even to open my editor with this project so it is kinda delayed.

**Comment by Ingiboy** [comment]
Было бы здорово, если бы ваш прокси остался таким, как есть - без лишних наворотов. Просто надежно и быстро работал, мало потребляя. Это хороший продукт для внутреннего потребления, когда нет потребности в промотированных каналах)

**Comment by 9seconds** [comment]
@Ingiboy в этом есть смысл, и лично я им так и планирую продолжать пользоваться, без каналов и тп. Но вокруг меня точно есть сообщества, которые хотят пользоваться promoted channels, но не столько для монетизируемой рекламы, сколько для выделенного канала оповещений. Скажем, чатик погромистов с отдельным промотед-каналом для объявлений о митапах, попойках, покупке Гитхаба Майкрософтом и сдаче квартир знакомым ноготочки на дому.

**Comment by Ingiboy** [comment]
@9seconds, м, в общем, да, согласен, фича имеет место быть в таком виде.

**Comment by Ingiboy** [comment]
Сергей, подскажите еще такой момеет: насколько ваш прокси «продакшн»? В том смысле, что есть ли в нем какие-то вещи, которые надо доработать (я не про промоканалы) или он уже может использоваться как «запустил и забыл»?

**Comment by 9seconds** [comment]
Ну, я сейчас им сам в таком режиме и пользуюсь, запустил и забыл :)12:30, 9 июня 2018 г., Ingiboy <notifications@github.com>:Сергей, подскажите еще такой момеет: насколько ваш прокси «продакшн»? В том смысле, что есть ли в нем какие-то вещи, которые надо доработать (я не про промоканалы) или он уже может использоваться как «запустил и забыл»?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


-- sergey arkhipov

**Comment by slytomcat** [comment]
Мне кажется, что если фича promoted channels будет неактивна, если не настроена - то существующий продукт не пострадает от нее - не хочешь - не настраивай (запустил и забыл), а надо - настрой и пользуйся.

**Comment by 9seconds** [comment]
@slytomcat все так. Я планирую ее сделать в том же ключе, что и https://github.com/alexbers/mtprotoproxy: если тега нет, то используем существующий подход. Есть - ходим через middle proxies. Надеюсь, на этих выходных (и следующей неделе) у меня будет время добить каналы

**Comment by Ingiboy** [comment]
Насколько сложно будет реализовать фичу с варьируемым размером пакетов? Чтобы противостоять блокировкам ростелека

**Comment by Ingiboy** [comment]
На мой взгляд, проект уже дошел до той стадии, где от создателя нужны комменты типа «это бета» или «это релиз, обновляйтесь»)

**Comment by EdgarSedov** [comment]
Ребят, а я правильно понимаю, что варьирумый размер пакета должен быть между клиентом и проксей, а не проксей и серверами телеги?

**Comment by 9seconds** [comment]
Конечно. Блокируют-то "последнюю" милю

**Comment by 9seconds** [comment]
Готово. Пока в состоянии беты, но у меня все работает без сбоев.

Done. In beta state so far but I see no problems.
