### ISSUE TITLE
Questions about the new version

### ISSUE THREAD

**Issue by pexcn** [9seconds/mtg#105]
Hi @9seconds :

For the new version, I found some problems, here are some questions and suggestions.

1. Whether the unit of buffer is `KB` or `Byte`?
```bash
# mtg run -h
...
  -w, --write-buffer=65536KB     Write buffer size in bytes. You can think about it as a buffer from client to Telegram.
  -r, --read-buffer=131072KB     Read buffer size in bytes. You can think about it as a buffer from Telegram to client.
...
```
But README refers to `Bytes`, and output log seems to be `KB`?
```bash
mtg run ************** -d
{"level":"debug","ts":1573540998.8162146,"msg":"Configuration","config":{"adtag":null,"anti_replay_max_size":134217728,"bind":{"IP":"0.0.0.0","Port":3128,"Zone":""},"cloak_host":"bing.com","cloak_port":443,"debug":true,"multiplex_per_connection":50,"public_ipv4":{"IP":"*.*.*.*","Port":3128,"Zone":""},"public_ipv6":{"IP":"*.*.*.*","Port":3128,"Zone":""},"read_buffer":134217728,"secret":"**************","secret_mode":2,"stats_addr":null,"stats_bind":{"IP":"127.0.0.1","Port":3129,"Zone":""},"stats_namespace":"mtg","statsd_network":"udp","statsd_tags":{},"statsd_tags_format":1,"verbose":false,"write_buffer":67108864}}
```

2. ~~On a machine with IPv6, can I use IPv4 to connect telegrams first? Can you add a `--ipv6-frist` option to set use IPv6 first, default priority to IPv4?~~
Is the new version already the default IPv4 first?

3. Can you add a option to disable the statsd function?

**Comment by L11R** [comment]
@pexcn 
1. It's bytes, but parser understands suffixes like KB or MB, so you you are free to use them.
3. You can just not pass `MTG_STATSD_ADDR` env var to disable it.

**Comment by pexcn** [comment]
@L11R 
The default buffer size seems to be wrong, can be seen from the log:
```
... "read_buffer":134217728, ... "write_buffer":67108864 ...
```
134217728 Bytes ≈ 134 MB
67108864 Bytes ≈ 67 MB

This seems too big, is it reasonable?

**Comment by L11R** [comment]
@pexcn I don't know is it reasonable or not, but this numbers is from source code:
https://github.com/9seconds/mtg/blob/596fafe30ddb05dfe5cfcaba8b66b1055462ced4/main.go#L90-L100

**Comment by pexcn** [comment]
Seems a typo, "65536KB" should be "65536B"?
cc @9seconds

**Comment by 9seconds** [comment]
This is typo, guys. Let me fix it now
