### ISSUE TITLE
Cannot boot new version

### ISSUE THREAD

**Issue by L11R** [9seconds/mtg#106]
I am trying to deploy v1.0, but getting this error:
```go
panic: cannot connect to the masked host: dial tcp my.pub.ip:443: connect: connection refused

goroutine 1 [running]:
mtg/faketls.Init.func1()
	/home/l11r/projects/mtg/faketls/init.go:35 +0x299
sync.(*Once).doSlow(0xe08a50, 0xc000165938)
	/usr/lib/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
	/usr/lib/go/src/sync/once.go:57
mtg/faketls.Init(0xa68ce0, 0xc0000682c0)
	/home/l11r/projects/mtg/faketls/init.go:23 +0x7c
mtg/cli.Proxy(0x0, 0x0)
	/home/l11r/projects/mtg/cli/proxy.go:79 +0x5b1
main.main()
	/home/l11r/projects/mtg/main.go:157 +0x768
```
I use this command to run it:
```bash
sudo ./mtg run --bind=my.pub.ip:443 --public-ipv4=my.pub.ip:443 --stats-bind=localhost:8443 eeSECRET
```
I cannot use `--bind=0.0.0.0:443`, because I have nginx running at another public IP.

**Comment by 9seconds** [comment]
Do you have any TLS server running on my.pub.ip:443? We need to dial to the masked host first in order to obtain a length of certificate.

**Comment by L11R** [comment]
@9seconds no, TLS server runs at another public IP. I generate new secret with hexed google.com domain, and now it boots... But I cannot connect to it.

**Comment by 9seconds** [comment]
Do you want to mask your proxy as this public IP? If so, I can give you some instructions. If want to troubleshoot google.com cloaking, let's do it :) Please share logs

**Comment by L11R** [comment]
Public IP that I used was blocked by RKN... I can only recommend to check your public IP at services like isitblockedinrussia.com.

Issue is now resolved, I changed IP and everything works fine.
