### ISSUE TITLE
Accurately identified by GFW and then banned

### ISSUE THREAD

**Issue by virgil710** [9seconds/mtg#111]
After I built an MTProxy from your docker last night, after a day and a half, my Telegram couldn't connect to my MTProxy. And my server is not banned.
Is there any way to fight GFW now? Chinese people need freedom of speech very much.

**Comment by pexcn** [comment]
Cannot reproduce, are you using tls mode?

**Comment by virgil710** [comment]
NO.
I followed the README.md deployment, I configured it according to the following command:
`docker run --name mtg --restart=unless-stopped -p 3128:3128 -d nineseconds/mtg:stable dd$(openssl rand -hex 16)`
In order to reduce the chance of being discovered by GFW, I did not map port 3129.
I originally wanted to use Faketls, but I don't know how to use it.

**Comment by virgil710** [comment]
> 无法复制，您使用的是tls模式吗？

没有。
我遵循了README.md部署，并根据以下命令对其进行了配置：
docker run --name mtg --restart=unless-stopped -p 3128:3128 -d nineseconds/mtg:stable dd$(openssl rand -hex 16)
为了减少被GFW发现的机会，我没有映射端口3129。
我最初想使用Faketls，但是我不知道如何使用它。

**Comment by virgil710** [comment]
> Cannot reproduce, are you using tls mode?

NO.
I followed the README.md deployment, I configured it according to the following command:
docker run --name mtg --restart=unless-stopped -p 3128:3128 -d nineseconds/mtg:stable dd$(openssl rand -hex 16)
In order to reduce the chance of being discovered by GFW, I did not map port 3129.
I originally wanted to use Faketls, but I don't know how to use it.

**Comment by pexcn** [comment]
You should use tls mode, other modes have been detected by gfw at least half year ago.

**Comment by pexcn** [comment]
e.g.:
```bash
mtg run -b 0.0.0.0:443 <YOUR_SECRET_KEY>
```

**Comment by virgil710** [comment]
> e.g.:
> 
> ```shell
> # get secret key
> mtg generate-secret tls -c bing.com
> 
> mtg run -b 0.0.0.0:443 <YOUR_SECRET_KEY>
> ```

I will try.
Thank you.

**Comment by virgil710** [comment]
> e.g.:
> 
> ```shell
> # get secret key
> mtg generate-secret tls -c bing.com
> 
> mtg run -b 0.0.0.0:443 <YOUR_SECRET_KEY>
> ```

```
When I run this command, the CLI gives me the following information:
 ./mtg generate-secret tls -c bing.com
mtg: error: unknown short flag '-c', try --help

Which step is wrong?
`
wget https://github.com/9seconds/mtg/archive/0.16.tar.gz
tar -xvf 0.16.tar.gz
cd mtg-0.16/
make
./mtg generate-secret tls -c bing.com
mtg: error: unknown short flag '-c', try --help
`
```

**Comment by pexcn** [comment]
@virgil710 Try latest version, you need to compile it yourself.

**Comment by virgil710** [comment]
> 
> 
> @virgil710 Try latest (latest commit) version, you need to compile it yourself.
> 
> You'd better use the docker version, the author provide the images.

I will try again.

**Comment by virgil710** [comment]
I think the latest docker image may have wrongs?
When I run `docker run --name mtg --restart=unless-stopped -p 3128:3128 -d nineseconds/mtg:latest dd$(openssl rand -hex 16)`
and then run `docker logs mtg` ,
the system feedback to me 
`mtg: error: expected command but got "dd31db05edcbd95815b1860f9268809b67", try --help
mtg: error: expected command but got "dd31db05edcbd95815b1860f9268809b67", try --help
mtg: error: expected command but got "dd31db05edcbd95815b1860f9268809b67", try --help
mtg: error: expected command but got "dd31db05edcbd95815b1860f9268809b67", try --help
mtg: error: expected command but got "dd31db05edcbd95815b1860f9268809b67", try --help
mtg: error: expected command but got "dd31db05edcbd95815b1860f9268809b67", try --help
mtg: error: expected command but got "dd31db05edcbd95815b1860f9268809b67", try --help
mtg: error: expected command but got "dd31db05edcbd95815b1860f9268809b67", try --help
mtg: error: expected command but got "dd31db05edcbd95815b1860f9268809b67", try --help
mtg: error: expected command but got "dd31db05edcbd95815b1860f9268809b67", try --help`

but I use stable image have no problems.

**Comment by pexcn** [comment]
Please read the README carefully.
You should not use `dd$(openssl rand -hex 16)` to generate secret key, TLS secret key starts with `ee`.

**Comment by virgil710** [comment]
Sorry,maybe I understand what you mean wrong,because my English is not good.
I have not `mtg` this command,I don't know where to execute this command.

**Comment by virgil710** [comment]
Now,docker feedback to me 
`
[root@01 ~]# docker logs mtg
Telegram demands secret of length 32
`

**Comment by pexcn** [comment]
My English not good too, but English is more common on GitHub.

In short, mtg using tls mode has the following two requirements:
1. build and install mtg latest version.
2. using `mtg` command to generate tls secret key.

**Comment by virgil710** [comment]
I solved it.
I hope that you can write the README in more detail to help more noobs like me.
THANKS.

**Comment by virgil710** [comment]
But getting down to business, I don't know if this method can effectively prevent being detected by GFW.

**Comment by pexcn** [comment]
According to README, you should use port 443 or another TLS port:
> FakeTLS - this mode envelops telegram stream in TLS so it looks (in theory) the same as any TLS1.3 traffic from DPI point of view.

**Comment by virgil710** [comment]
I tried,but I didn't feel any difference from the normal port.
