### ISSUE TITLE
cannot boot new version

### ISSUE THREAD

**Issue by lukemin** [9seconds/mtg#112]
after making the newest version, I use these commands to do it
go get github.com/9seconds/mtg
cd $HOME/mtg/src/github.com/9seconds/mtg
make
mv mtg /usr/local/mtproxy-go/mtg

when I run it, getting this error:
mtg: error: unknown short flag '-b', try --help

**Comment by pexcn** [comment]
Read: https://github.com/9seconds/mtg#upgrade-to-10

**Comment by 9seconds** [comment]
Yes, there is a change in command-line: you have to do `mtg run` instead of `mtg`
