### ISSUE TITLE
module not go-gettable

### ISSUE THREAD

**Issue by kaey** [9seconds/mtg#114]
Why was this done https://github.com/9seconds/mtg/commit/273aa183670e31fb962078f343c339c455aa4083 ?
The end result is this
```
$ go get github.com/9seconds/mtg
go: finding github.com/9seconds/mtg latest
go: downloading github.com/9seconds/mtg v0.0.0-20191118083057-ed9689d81303
go: extracting github.com/9seconds/mtg v0.0.0-20191118083057-ed9689d81303
go get: github.com/9seconds/mtg@v0.0.0-20191118083057-ed9689d81303: parsing go.mod:
        module declares its path as: mtg
                but was required as: github.com/9seconds/mtg
```

Also it would help if release tag was a semantic version, as required by go modules.
This way proper version info is recorded in a binary and can be viewed with `go version -m path/to/mtg` or https://godoc.org/runtime/debug#ReadBuildInfo. No need for ldflags anymore.

**Comment by 9seconds** [comment]
> Why was this done 273aa18 ?
> The end result is this

No particular reason, I just wanted to remove any mentions of github. Seems I have to return them back. Sorry, I didn't try to `go get` after this commit

> Also it would help if release tag was a semantic version, as required by go modules.

Thanks. I've clearly mistagged this release. I gonna make `v1.0.1` which will fix this issue.

> This way proper version info is recorded in a binary and can be viewed with go version -m path/to/mtg or https://godoc.org/runtime/debug#ReadBuildInfo. No need for ldflags anymore.

Didn't know about that either. Thanks a lot, I gonna move to this one.

**Comment by kaey** [comment]
>I just wanted to remove any mentions of github

You'll need publicly accessible vanity domain, see https://golang.org/cmd/go/#hdr-Remote_import_paths.

Thanks for taking your time to fix this.

**Comment by 9seconds** [comment]
Thanks. The only missing part is correct tag name. I gonna do it today or tomorrow
