### ISSUE TITLE
Can't generate secret

### ISSUE THREAD

**Issue by kolay-v** [9seconds/mtg#118]
After running ./run.sh it output Proxy secret is . Port is 443. I also tried generate secret by my self. But command don't output anything. 
```kolayv@instance-1 ~/mtg>
sudo docker run --rm nineseconds/mtg generate-secret tls -c bing.com
kolayv@instance-1 ~/mtg>
```

I tried both stable and latest images

**Comment by 9seconds** [comment]
I do not have any problems there :/

```console
➜ docker run --rm nineseconds/mtg generate-secret tls -c bing.com
ee2ffff5ffcf57e74e72702df57db0ded662696e672e636f6d
```

After I've checked `run.sh` again, I have one assumption: docker should be available for non-root user. https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user Could you please check?

**Comment by 9seconds** [comment]
I've made run.sh more robust. Could you please check again?

**Comment by kolay-v** [comment]
Now run.sh doesn't work with sudo at all. But adding user to docker group and executing run.sh without sudo works. Thank you for help.

**Comment by 9seconds** [comment]
Great to hear
