### ISSUE TITLE
Can not make from source

### ISSUE THREAD

**Issue by BorBorisych** [9seconds/mtg#119]
Having downloaded source (https://github.com/9seconds/mtg/archive/master.zip) and trying to run the "make" I get the following error:
---
go: github.com/VictoriaMetrics/fastcache@v1.5.2 requires
        github.com/cespare/xxhash/v2@v2.0.1-0.20190104013014-3767db7a7e18: invalid version: git fetch --unshallow -f https://github.com/cespare/xxhash in /home/mtg_proto/go/pkg/mod/cache/vcs/9d94b3ef213c7f305d29c159464a6c33cfe16c4bfb738a285df93010f541eb59: exit status 128:
        fatal: git fetch-pack: expected shallow list
        fatal: The remote end hung up unexpectedly
make: *** [mtg] Error 1
---

Is there any way to fix it? I'd like to make the executable from source to get rid of "Cannot pump sockets" message in log (I simply comment this string of logging code with /* */ in direct.go file). I mentioned about it some time ago here - https://github.com/9seconds/mtg/issues/69

Thank you in advance!

**Comment by 9seconds** [comment]
This is really weird. I gonna update dependencies to eliminate that.

**Comment by 9seconds** [comment]
Please try again

**Comment by BorBorisych** [comment]
Sorry, but the error still exists. Used master source.

`go: github.com/VictoriaMetrics/fastcache@v1.5.2 requires
        github.com/cespare/xxhash/v2@v2.0.1-0.20190104013014-3767db7a7e18: invalid version: git fetch --unshallow -f https://github.com/cespare/xxhash in /home/mtg_proto/go/pkg/mod/cache/vcs/9d94b3ef213c7f305d29c159464a6c33cfe16c4bfb738a285df93010f541eb59: exit status 128:
        fatal: git fetch-pack: expected shallow list
        fatal: The remote end hung up unexpectedly
make: *** [mtg] Error 1`

**Comment by 9seconds** [comment]
I'm wondering if you have any problems with access to GitHub. To verify that, could you please do the following commands?

```console
$ go clean -cache -modcache
$ go build -v -x
```

Please collect the output and post it to some pastebin or gist

**Comment by BorBorisych** [comment]
Thanks a lot - having the cache cleaned ($go clean -cache -modcache) I successfully made the executable.
