### ISSUE TITLE
Try connect with IPv6 not IPv4

### ISSUE THREAD

**Issue by maysammortazi** [9seconds/mtg#128]
sorry about my english
after update my proxy not working:
when i run with -v :
`{"level":"info","ts":1580219153.4684043,"logger":"telegram.direct","msg":"Cannot dial to Telegram","address":"[2001:b28:f23d:f001::a]:443","error":"dial tcp [2001:b28:f23d:f001::a]:443: connect: network is unreachable"}`

my server has only ipv4 but it want to connect on ipv6, may it cause my problem.
Thanks

**Comment by 9seconds** [comment]
If your server has only ipv4, then it is absolutely not a problem. mtg tries to connect to both ipv4 and ipv6 and picks up the first working one.

**Comment by maysammortazi** [comment]
Thanks
