### ISSUE TITLE
Connection issues with the latest Android client

### ISSUE THREAD

**Issue by KonishchevDmitry** [9seconds/mtg#132]
Hi!

It looks like Telegram has changed something in their latest release for Android (version 5.15.0) which makes it unusable with mtg.

It perfectly connects to proxy, but after some time (minutes) goes to infinite "Connecting to proxy" state.

In mtg logs it looks like:
```
{"level":"warn","ts":1581853188.4431674,"logger":"proxy","msg":"Cannot perform client handshake","connection_id":"e61cf70b789910c7","error":"failed tls handshake: bad time"}
```
([here](https://github.com/9seconds/mtg/blob/master/faketls/client_protocol.go#L83)).

I've added a trivial debug message using `fmt.Printf(">>> %d\n", timestamp - time.Now().Unix())` and see that on initial connection I get `0`/`1` difference, but when Telegram opens new connections, it starts to drift to larger values `-73`, `-206`, `-566`...

I've had no time yet to get into the protocol details what exactly this timestamp means, but now it's definitely broken. I didn't try to measure it with stopwatch, but at first sight it looks like Telegram uses connection pool creation time instead of TCP connection creation time.

**Comment by 9seconds** [comment]
Thanks for the report, I also met this issue :(

It was introduced by Telegram: https://github.com/DrKLO/Telegram/commit/2eafc07314532d9ec31bdb63378a30a4969c26db and fixed here: https://github.com/DrKLO/Telegram/commit/df90eface5ebd755ea86c3a4eec66fe5b6e29041 So, please consider updating from Play Store
