### ISSUE TITLE
Low speed

### ISSUE THREAD

**Issue by godali645** [9seconds/mtg#133]
Hi my ping is high and my download speed is very low.
can you give me complite command ro run?

and every one day isp bolcked proxy.
can you give solution?

and max number of user can to connecting , how many?

i want the best config for proxy?

**Comment by 9seconds** [comment]
> Hi my ping is high and my download speed is very low.

This could be by many reasons. Are you sure that proxy<->telegram is a bottleneck but not your connectivity to proxy?

> can you give me complite command ro run?

Please see this script: https://github.com/9seconds/mtg/blob/master/run.sh

> and every one day isp bolcked proxy.
> can you give solution?

The best solution so far is to use faketls mode (secrets with `ee` prefix)

> and max number of user can to connecting , how many?

There is no artificial limit. It can be any number.

**Comment by godali645** [comment]
ok . 
 use faketls mode so tell me some faketls?

and when client connect .
message sending and getting is good but download is too bad.why?

(cannot extract obfuscated 2 frame: read tcp)

**Comment by 9seconds** [comment]
If the download speed is too bad, I expect that there might be a lot of loss of TCP packets due to bad connectivity. Could you please test connectivity to this proxy? I would recommend you to use iperf for that
