### ISSUE TITLE
Server types clarification

### ISSUE THREAD

**Issue by luminoso** [9seconds/mtg#147]
Hi! I was doing some experiments with this MTProxy implementation and there are a few things that are not clear.

1. What is the purpose of simple type? Compatibility with older clients?

2. Are these affirmations true?

- FakeTLS is incompatible with Simple and Secured server type
- Simple and secured type are compatible. It depends if the client adds (or not) the "dd" prefix and the server will add the random noise or not.

3. Is this the expected behavior of FakeTLS?

Create a new key
```
$ ./mtg-linux-amd64 generate-secret -c google.com tls
eea687ab0406066ab5b89cb6e815e19a94676f6f676c652e636f6d
```

Start the server

`$ ./mtg-linux-amd64 run -v eea687ab0406066ab5b89cb6e815e19a94676f6f676c652e636f6d`

Proxy works fine in the Telegram apps

But if I cur the proxyl using an external machine I see no cloaked response?

```
$ curl -vL mtproxy.now.im:3128 
*   Trying 2a01:4f8:c0c:4b74::1:3128...
* Connected to mtproxy.now.im (2a01:4f8:c0c:4b74::1) port 3128 (#0)
> GET / HTTP/1.1
> Host: mtproxy.now.im:3128
> User-Agent: curl/7.69.1
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host mtproxy.now.im left intact
curl: (52) Empty reply from server
```

Server output:
`{"level":"warn","ts":1590870839.7453997,"logger":"proxy","msg":"Cannot perform client handshake","connection_id":"34ced4f33434c8ba","error":"failed first bytes of tls handshake"}`

Is this the expected cloaked response?

**Comment by 9seconds** [comment]
Hi!

1. Yes, you are absolutely correct. Just for backward compatibility and software archeology.
2. You are absolutely correct. dd-secrets were introduced by Telegram team to allow smooth migration from simple to secure mode.
3. When you do `curl -vL mtproxy.now.im:3128`, you are trying to connect via HTTP but this port is for HTTPS only (curl does not try to establish TLS connection there, it just sends HTTP/1.1 via plain TCP). You need to run curl as `curl -vL https://mtproxy.now.im:3128`. It is the same even with Google:

```console
$ curl -vL google.com:443
*   Trying 216.58.207.206:443...
* Connected to google.com (216.58.207.206) port 443 (#0)
> GET / HTTP/1.1
> Host: google.com:443
> User-Agent: curl/7.70.0
> Accept: */*
>
* Empty reply from server
* Connection #0 to host google.com left intact
curl: (52) Empty reply from server
```

**Comment by luminoso** [comment]
Thank you! I sucessfuly replicated the cloaked response.

Is there any disadvantage of running FakeTLS server type? It looks like it only has advantages.

**Comment by 9seconds** [comment]
No disadvantages :) I would even say that all other types are kept for backward compatibility.

**Comment by luminoso** [comment]
> No disadvantages :) I would even say that all other types are kept for backward compatibility.

humm that I cannot replicate. Once in FakeTLS type, even if I try with simple or secured secret it doesn't connect.

However secured and simple are compatible with a single server instance

**Comment by 9seconds** [comment]
Faketls secret is compatible with faketls servers only

**Comment by luminoso** [comment]
Alright. Do you also confirm that FakeTLS is incompatible with @MTProxybot ? It never displays statistics when this server type is activated

**Comment by luminoso** [comment]
Now makes sense. After testing now I understand that only with "Middle" I can do this:

![imagem](https://user-images.githubusercontent.com/296323/83940005-3197df80-a7d9-11ea-8fbd-1e9626918d5c.png)

Thank you. I have all the clarifications that I need!

**Comment by luminoso** [comment]
For fun, this was the result: https://mtproxy.now.im/

Lets see how it goes. Thank you for your implementation :+1:
