### ISSUE TITLE
-b command broken?

### ISSUE THREAD

**Issue by delphinuz** [9seconds/mtg#153]
./mtg -b 0.0.0.0 -p  xxxxx x.x.x.x -q xxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
mtg: error: unknown short flag '-b', try --help
mtg: error: unknown short flag '-b', try --help
mtg: error: unknown short flag '-b', try --help

 ./mtg  --version
v1.0.5 (go version go1.14.1 linux/amd64) [Tue, 31 Mar 2020 07:13:51 +0000]

**Comment by 9seconds** [comment]
Please pass `run` as command: `./mtg run -b 0.0.0.0 -p xxxxx x.x.x.x -q xxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`. This was a backward incompatible change made in 1.0 release. Please see the README, last chapter.
