### ISSUE TITLE
How to multiplex mtg and Nginx on port 443?

### ISSUE THREAD

**Issue by freejohn123** [9seconds/mtg#158]
I want to set up a FakeTLS MTProto proxy, with a real Nginx web server behind it.

- Telegram users should reach mtg
- Browser users should get a response from Nginx

I have mtg listening on port 443. I have Nginx listening on port 993, but I cannot visit the website in a browser.

Is this correct: 

`mtg run <SECRET> -b 0.0.0.0:443 --cloak-port 993`

**Comment by freejohn123** [comment]
Maybe do the same as the working example at the end of #152 ?

**Comment by freejohn123** [comment]
It is working now. I don't know why it didn't work before. Complete procedure is documented at https://github.com/freejohn123/mtproto-tls-server

**Comment by 9seconds** [comment]
Thanks a lot!

**Comment by alsotang** [comment]
is your solution still works? see https://github.com/9seconds/mtg/issues/162#issuecomment-830086817
