### ISSUE TITLE
Cannot start with adtag at all, without it works with some warns

### ISSUE THREAD

**Issue by L11R** [9seconds/mtg#16]
Without *adtag* works but with erros in log:
```json
{
  "level": "error",
  "ts": 1531255859.299111,
  "logger": "main",
  "msg": "Cannot initialize client connection",
  "connection_id": "57c86d29-b0a8-48d5-94cc-2c81482319b7",
  "error": "Cannot parse obfuscated frame: Unknown protocol: Unknown handshake protocol",
  "errorVerbose": "/home/vagrant/safe/go/src/github.com/9seconds/mtg/mtproto/connection_options.go:79: Unknown handshake protocol\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/obfuscated2/obfuscated2.go:40: Unknown protocol\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/client/direct.go:45: Cannot parse obfuscated frame"
}
```

With it can't connect at all:
```json
{
  "level": "error",
  "ts": 1531256123.8771994,
  "logger": "main",
  "msg": "Cannot initialize server connection",
  "connection_id": "6f294179-cdfa-43b0-bcf4-d53e1c49eae2",
  "error": "Cannot handshake telegram: Cannot read RPC nonce response: Cannot read frame padding: EOF",
  "errorVerbose": "EOF\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/wrappers/mtproto_frame.go:52: Cannot read frame padding\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/telegram/middle.go:71: Cannot read RPC nonce response\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/proxy/proxy.go:103: Cannot handshake telegram"
}
```

My VPS is under NAT so I provide port, local and public addressed. I use precompiled binary from Releases.

**Comment by L11R** [comment]
Errors in log with unknown protocol were caused by my mobile phone with old non-dd secret, so first problem solved, but still can't get it work with adtag.

**Comment by 9seconds** [comment]
Yes, these dd-secrets are supported not in all clients. Regarding the second issue: I do not have any machine with ipv6 at this moment so cannot verify why it happens. I'll do that later this week

**Comment by 9seconds** [comment]
Could you also please upload the whole log somewhere to pastebin?

**Comment by L11R** [comment]
@9seconds ofc: https://gist.github.com/L11R/129357aedbbb22f926585657b4007bef

**Comment by 9seconds** [comment]
@L11R Is it possible that your time is not synchronized with NTP? I see that mtg connects to Telegram but cannot do simple RPC nonce request. Usually, it happens if your time is not synchronized.

**Comment by L11R** [comment]
@9seconds, yeah, I already thought about it. And yes, I have small desync ~25-30 seconds, but my VPS is an OpenVZ container, so I can't sync it...

**Comment by 9seconds** [comment]
This is huge :/ IIRC Telegram cannot tolerate difference bigger than a couple of seconds.

**Comment by 9seconds** [comment]
Can you create a ticket for your VPS provider? This is an issue they have to fix.

**Comment by L11R** [comment]
Got it, okay, thanks for help!
