### ISSUE TITLE
How to add myproxy in FakeTLS mode to MTProxybot？

### ISSUE THREAD

**Issue by xiaoliduck** [9seconds/mtg#164]
It seems that MTproxybot only support 32 hex secret, but secure and TLS mode's secrets are both more than 32.

**Comment by 9seconds** [comment]
Good point, I need to update documentation. Meanwhile, you can start mtg and check its stdout. You'll see some JSON here. Please find a field called `secret_for_mtproxybot`. A value of this field will contain a derived secret you have to supply to that bot.

**Comment by Nutr1t07** [comment]
Hi and what is the status about it now? I dont seem to find that field from `mtg access /etc/mtg.toml`.

**Comment by 9seconds** [comment]
Hey! Please see here: https://github.com/9seconds/mtg#version-2 You need to use version 1 to get it
