### ISSUE TITLE
I can not boot "./mtg run <secret>"

### ISSUE THREAD

**Issue by 1Bob2TM** [9seconds/mtg#167]
First I run "./mtg generate-secret -c google.com tls"
And then run "./mtg run ee852380f362a09343efb4690c4e17862e676f6f676c652e636f6d

Result:
fatal error: cannot initialize stats server: listen tcp 127.0.0.1:3129: bind: cannot assign requested address

**Comment by 9seconds** [comment]
You have something working on 3129 port. You can try to reassign stats endpoint somewhere else.
