### ISSUE TITLE
Couple Easy Questions

### ISSUE THREAD

**Issue by rogueops** [9seconds/mtg#170]
I am using docker and using the oneliner and I would like to change the port, i changed it in the run.sh, is this method correct? If not how can I change it? Also the secret the oneliner generates is very, very, long, so I wanted to cut it in half to start, i see the section showing "generate-secret tls -c "$(openssl rand -hex 16).com". Since the length is longer than 16, its creating a secret of 106 characters so I want to drop it down to 32 so what should I update to get 32 characters instead of 106?

Thanks for the help!

**Comment by 9seconds** [comment]
> I am using docker and using the oneliner and I would like to change the port, i changed it in the run.sh, is this method correct?

Sure, why not. This script is just a wrapper which pass cli parameters.

> Since the length is longer than 16, its creating a secret of 106 characters 

Why so? It has 16 bytes. 16 bytes in hex is 16*2 = 32.

```console
$ echo -n $(openssl rand -hex 16) | wc -c
32
```

**Comment by rogueops** [comment]
no idea, when I look at the secret its 106 using the oneliner as is
with the docker image

**Comment by 9seconds** [comment]
To be honest, I do not know what to do here :/
