### ISSUE TITLE
What is the secure mode?

### ISSUE THREAD

**Issue by VictoriaRaymond** [9seconds/mtg#18]
Is there a spec for the secure mode (with tag '0xdd')? What's the difference between this one and the abridged mode?

**Comment by 9seconds** [comment]
Hey! No, unfortunately, we have no specs. We investigate sources of Telegram clients and official proxy to understand what is going on there. If I understand correctly, the main point of having this secret mode is to allow Telegram/client to use random paddings to make it harder to detect patterns in the traffic.

**Comment by 9seconds** [comment]
I hope I answered your question. Feel free to reopen!
