### ISSUE TITLE
github docker registry url is broken

### ISSUE THREAD

**Issue by alsotang** [9seconds/mtg#186]
I found https://github.com/users/9seconds/packages/container/package/mtg in readme. but it is broken.

**Comment by alsotang** [comment]
and `docker pull nineseconds/mtg:2` does not work

**Comment by pexcn** [comment]
I also made a docker image of mtg, it based on `v2.0.0-rc1`, e.g.:
```bash
docker run pexcn/docker-images:mtg <bind-to> <secret>

docker run -d \
  --name mtg \
  --restart unless-stopped \
  --network host \
  pexcn/docker-images:mtg 0.0.0.0:993 7kgi5pN2PoUloLUu4FPEVDJ3d3cuYmluZy5jb20
```

**Comment by 9seconds** [comment]
@alsotang sorry for that. You are right, url is broken. For now, you can check what we have in GHCR: https://github.com/users/9seconds/packages/container/mtg/versions Also, there is a tag in docker hub: https://hub.docker.com/layers/nineseconds/mtg/2.0.0-rc1/images/sha256-8b3e7af8555d9ea833168f29f693822b455a1e6c511544111395e2fc945574ea?context=explore
