### ISSUE TITLE
mtg access returns wrong address

### ISSUE THREAD

**Issue by vdrandom** [9seconds/mtg#190]
mtg seems to use the default ip for uris it returns when a user runs `mtg access /path/to/config.toml`. The thing is, it can be bound to any address present (e.g. localhost, for tcp proxy).

It's obviously a cosmetic thing, but it would be nice to be able to set external address / hostname in the settings instead of fixing uris manually. Especially since without it mtg tries to guess and may guess wrong.

**Comment by vdrandom** [comment]
Makes sense, thanks.

But it would be nice to have a config option for that as well.

**Comment by 9seconds** [comment]
But this value won't be used for a proxy itself. This is mostly to make and share a link to a friend :/ I'm still not really sure if such ad-hoc thing deserves an option in a file.

**Comment by 9seconds** [comment]
Since this is not an issue anymore, I'm converting this to discussion.
