### ISSUE TITLE
OS packages

### ISSUE THREAD

**Issue by 9seconds** [9seconds/mtg#193]
I've integrated goreleaser and it looks like a good idea of having OS packages here. But here is the thing: we need to create correct pre and post-install scripts to startup systemd. It looks like a trivial task but apparently this is tricky to use dh-systemd with goreleaser and I'm not sure how to make these scripts because I'm not really familiar with these details.

Any help with making correct OS packages + scripts is appreciated.

**Comment by lynkco01** [comment]
One click install
https://github.com/cutelua/mtg-dist

**Comment by missuo** [comment]
One-Click Install
