### ISSUE TITLE
unfiltering the proxies.

### ISSUE THREAD

**Issue by hossein7596** [9seconds/mtg#196]
thank you for your wonderful method Sir. but in iran proxies become unusable after a while because they become banned and filtered by ISPs. do you have any idea for unfiltering proxis when are used vastly by many users? thanks again.

**Comment by lynkco01** [comment]
@hossein7596  Creating a whitelist through the server firewall can be effective against GFW blocking, I don't know if this applies to Iran, you can try this method.

**Comment by hossein7596** [comment]
> @hossein7596 Creating a whitelist through the server firewall can be effective against GFW blocking, I don't know if this works properly in Iran, you can try this method.

thanks again... i will try it... with the best...

**Comment by 9seconds** [comment]
mtg already has a support of ip blocklists. Please check out if it works for you: https://github.com/9seconds/mtg/blob/master/example.config.toml#L140-L162
