### ISSUE TITLE
Error at build in windows

### ISSUE THREAD

**Issue by FDeghy** [9seconds/mtg#212]
# github.com/9seconds/mtg/v2/network
network\sockopts.go:57:9: undefined: unix.SetsockoptInt
network\sockopts.go:57:37: undefined: unix.SOL_SOCKET
network\sockopts.go:57:54: undefined: unix.SO_REUSEADDR
network\sockopts.go:64:9: undefined: unix.SetsockoptInt
network\sockopts.go:64:37: undefined: unix.SOL_SOCKET
network\sockopts.go:64:54: undefined: unix.SO_REUSEPORT

**Comment by 9seconds** [comment]
Should be fixed by https://github.com/9seconds/mtg/pull/209 or similar one
