### ISSUE TITLE
Whitelist support

### ISSUE THREAD

**Issue by EkkoG** [9seconds/mtg#218]
Whitelist is useful to protect the proxy, to prevent being baned, https://github.com/9seconds/mtg/issues/196#issuecomment-855385838

Blacklist is useful for ACL, but for this usage, blacklist is very convenient, whitelist is a better choice, so I create this feature request, thanks for your great work.

I read a little code, maybe it's easy to add this feature, copy blacklist's code, and adjust this algorithm will make this feature work. https://github.com/9seconds/mtg/blob/ce8f1ebb6c0b56ee157e17a905f10086418b3b32/mtglib/proxy.go#L112

**Comment by cielpy** [comment]
I think the same as blacklist is enough, http handler has another benefit is another process can update the list dynamically.

BTW, what format does `update-each` need? https://github.com/9seconds/mtg/blob/bae54073722f40b3af0e22695736972f768a1fd2/example.config.toml#L175

and the minimum update frequency we can set?
