### ISSUE TITLE
does it support Ubuntu ARM machine?

### ISSUE THREAD

**Issue by cary-sas** [9seconds/mtg#225]
I build the proxy on ubuntu arm machine, however, the client cannot connect it , why?

**Comment by 9seconds** [comment]
There might be tons of reasons. Could you please share some logs?

**Comment by cary-sas** [comment]
it's strange, maybe it is due to the setting of VPS,  I use the same one on another machine, it works fine. Only in Oracle VPS cannot work.  There is no error info in the logs.

**Comment by cary-sas** [comment]
how to enter the container, I try to `docker exec -it mtg bash`, but it failed.
`OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "bash": executable file not found in $PATH: unknown`

**Comment by cary-sas** [comment]
it's strange, I changed the port, then everything works now

**Comment by 9seconds** [comment]
Docker image is built from scratch. There is no any shell inside
