### ISSUE TITLE
Multi proxy cannot reconnect when the uplink proxy provider restart

### ISSUE THREAD

**Issue by zzzz0317** [9seconds/mtg#267]
I use V2Ray as the uplink proxy, when I restart V2ray, mtg cannot reconnect V2ray via socks5 until I restart mtg.

```
{"level":"warn","logger":"proxy","error":"cannot dial to Telegram: cannot dial to 3 dc: cannot dial to tcp4:149.154.175.100:443: cannot dial with all proxies","timestamp":1651484189896,"message":"cannot dial to telegram"}
```

I tried the following proxies config
```
proxies = [
    "socks5://127.0.0.1:1024?open_threshold=5&half_open_timeout=1m&reset_failures_timeout=10s",
    "socks5://127.0.0.1:1022?open_threshold=5&half_open_timeout=1m&reset_failures_timeout=10s"
]
```
```
proxies = [
    "socks5://127.0.0.1:1024/?open_threshold=5&half_open_timeout=10s&reset_failures_timeout=5s",
    "socks5://127.0.0.1:1022/?open_threshold=5&half_open_timeout=10s&reset_failures_timeout=5s"
]
```
```
proxies = [
    "socks5://127.0.0.1:1024",
    "socks5://127.0.0.1:1022"
]
```

Single proxy is no problem, just few "cannot dial to the proxy" and then recovered.

**Comment by 9seconds** [comment]
Sorry for the delay, was offline. This works as expected. When you use a list of proxies, mtg uses [circuit breaker](https://en.wikipedia.org/wiki/Circuit_breaker_design_pattern) to access each one. So, if one fails, mtg detects it and prevents any attempt to access it for some time (see these `open_threshold` etc parameters). So, if you restart V2Ray, mtg tries to access and after some failures considers it dead. And prevents any connect for some time (this is tunable by parameters).
