### ISSUE TITLE
How to : Proxy chaining

### ISSUE THREAD

**Issue by privatesupport** [9seconds/mtg#273]
In documentation you said we can use mtg with socks 5 proxy (v2ray) as Proxy chaining. I cant find how to do it.
Is there any parameter or Flag to send socks 5 user and pass to mtg?

**Comment by 9seconds** [comment]
Please see this: https://github.com/9seconds/mtg/blob/master/example.config.toml#L90-L122 Roughly speaking, you need to provide a socks5 proxy to a list. This socks5 proxy could be v2ray interface or any other implementation. SOCKS5 is chosen as a lingua franca of all proxy implementations.
