### ISSUE TITLE
Error when running docker

### ISSUE THREAD

**Issue by amihos** [9seconds/mtg#275]
I get this error: 

docker: Error response from daemon: invalid volume specification: '/home/ubuntu/config.toml:config.toml': invalid mount config for type "bind": invalid mount path: 'config.toml' mount path must be absolute.

I created config file in the home directory and am running this from there:
docker run -d -v $PWD/config.toml:config.toml -p 443:3128 --name mtg-proxy --restart=unless-stopped nineseconds/mtg:2

**Comment by 9seconds** [comment]
You need to run it with `v $PWD/config.toml:/config.toml`. Please pay attention to a first slash immediately after colon: Docker demands to have an absolute path within a container
