### ISSUE TITLE
Question : replay attacks - Fake-TLS vs Secure randomized-packet-size

### ISSUE THREAD

**Issue by privatesupport** [9seconds/mtg#281]
I have two question.

Does this project have Protection from replay attacks ???

I have a VPS and I run a website with https on this server. For preventing from DPI detection, Fake-TLS protocol (use my website domain for fake tls domain) is better or secure mode with randomize packet size (Specially in countries like Iran) ????

**Comment by 9seconds** [comment]
Yes, the goal of the project is to harden security as much as possible. So, packet sizes are randomized on a MTRPOTO protocol level (mtg does not support middle proxies so it is not required to repack anything), FakeTLS is the only mode. [Protection from replay attacks](https://github.com/9seconds/mtg/blob/master/example.config.toml#L137-L153) is also present.

**Comment by privatesupport** [comment]
> Yes, the goal of the project is to harden security as much as possible. So, packet sizes are randomized on a MTRPOTO protocol level (mtg does not support middle proxies so it is not required to repack anything), FakeTLS is the only mode. [Protection from replay attacks](https://github.com/9seconds/mtg/blob/master/example.config.toml#L137-L153) is also present.

Thanks.
