### ISSUE TITLE
Petition to enable legacy mode in V2

### ISSUE THREAD

**Issue by terrytw** [9seconds/mtg#285]
Dear dev,

I think there is a user case for legacy mode, if one's configuration looks like this:

```
client--------mtg-------other proxy like shadowsocks-------shadowsocks server------telegram server
                                                       |
                                                       |
                                                   censorship
```

In this case, there is no censorship between telegram client and mtg.
And faketls, in my experience, seems to be more resource consuming, at least it takes around 15 seconds to connect each time I open telegram client.

**Comment by 9seconds** [comment]
FakeTLS is almost free because it does not do any encryption per se. Actually, this is literally the same traffic as in "legacy mode" (pure telegram traffic) but arranged in TLS records (I mean, literally, 1 byte of header, length of the message and message without any encryption).

What makes you think that FakeTLS is a reason?

**Comment by terrytw** [comment]
When I open telegram, there is a "connecting" notification on top,

in legacy mode, it goes away quickly, shows "connected" and I am able to send and receive messages.
in FakeTLS mode, it takes 15-30 seconds before "connected" shows up.

**Comment by terrytw** [comment]
Update: it seems to be related to time skew. 

The default 5s setting will cause telegram to failed to connect, about 50% of the time(estimation)
Anything between 10s to 120s will cause telegram to stuck at "connecting" for 15-30 seconds, but connection will be successful. 
Setting it to 300s, telegram can connect instantaneously.

**Comment by 9seconds** [comment]
Seems so. I'm not really sure how to communicate this timing problem to a user because usually mtg works in fire-and-forget mode. I have bugs of such nature from time to time https://github.com/9seconds/mtg/issues/284

**Comment by v03413** [comment]
> When I open telegram, there is a "connecting" notification on top,
> 
> in legacy mode, it goes away quickly, shows "connected" and I am able to send and receive messages. in FakeTLS mode, it takes 15-30 seconds before "connected" shows up.

如果在不过🧱的情况下，推荐使用 socks5 取代，能得到更好的体验效果。

**Comment by terrytw** [comment]
> > When I open telegram, there is a "connecting" notification on top,
> > in legacy mode, it goes away quickly, shows "connected" and I am able to send and receive messages. in FakeTLS mode, it takes 15-30 seconds before "connected" shows up.
> 
> 如果在不过🧱的情况下，推荐使用 socks5 取代，能得到更好的体验效果。

Exposing a socks5 proxy is just unnecessary security risk. Better experience is not only about easy to setup and use.

**Comment by v03413** [comment]
> 



> > > When I open telegram, there is a "connecting" notification on top,
> > > in legacy mode, it goes away quickly, shows "connected" and I am able to send and receive messages. in FakeTLS mode, it takes 15-30 seconds before "connected" shows up.
> > 
> > 
> > 如果在不过🧱的情况下，推荐使用 socks5 取代，能得到更好的体验效果。
> 
> Exposing a socks5 proxy is just unnecessary security risk. Better experience is not only about easy to setup and use.

的确是这样，但目前除了官方C语言版本，都或多或少存在一些问题，比较难搞。
