### ISSUE TITLE
error in launching docker container

### ISSUE THREAD

**Issue by bishiping** [9seconds/mtg#287]
At README, on this step : https://github.com/9seconds/mtg#run-a-proxy

    docker run -d -v $PWD/config.toml:/config.toml -p 443:3128 --name mtg-proxy --restart=unless-stopped nineseconds/mtg:2

missing /

**Comment by arashnm80** [comment]
yes the missing slash fixes this step.

**Comment by 9seconds** [comment]
Thanks. You can send PR if you want. I'll fix it later. Sorry, busy time for me

**Comment by arashnm80** [comment]
@bishiping
issue fixed in the latest pull request, now can be closed.

**Comment by 9seconds** [comment]
Thanks a lot!
