### ISSUE TITLE
use mtproto as an all-purpose tunnel

### ISSUE THREAD

**Issue by mosajjal** [9seconds/mtg#291]
hey there. thanks for the great project! 

quick question: is it technically possible to use this protocol to build an all-purpose tunnel. 

eg a client exposing a SOCKS on localhost:1080 and tunneling any TCP stream over mtproto to an mtproto server.

**Comment by 9seconds** [comment]
Hi! Sorry for the late reply: technically yes, it is doable I suppose but it really depends on what you are trying to build. This proxy is 100% bound to Telegram so if you want to use mtg here, you need to find a way how to bypass that: https://github.com/9seconds/mtg/tree/master/mtglib/internal

**Comment by mosajjal** [comment]
got it. I've looked into various censorship bypasses and `mtproto` has one of the best performances against a DPI. Although as you said it only works on TG platform so not sure if that holds up against arbitrary web surfing. I'll close this issue and will take a look at the code to see if I can open it up :)
