### ISSUE TITLE
Is the doh-ip = "9.9.9.9" option really taking effect?

### ISSUE THREAD

**Issue by cod1ingcoding** [9seconds/mtg#301]
I suspect that the `doh-ip = "9.9.9.9"` option did not have any practical effect, because when I used the tcpdump command `tcpdump -i eth0 -vnn host 9.9.9.9` on the server, I couldn't capture any data.

**Comment by 9seconds** [comment]
It really depends on your usage pattern because proxy itself requires very little traffic. Actually, nothing. It is used only for socks proxy address lookups, getting blocklists etc. If these features are not used, then of course no lookups are performed.

Can you share your config?

**Comment by cod1ingcoding** [comment]
@9seconds 
I'm not using an upstream proxy or blocklist. Maybe that's why DOH requests aren't being made. When Telegram itself is passing through an MTProto (MTG) proxy, how does it initiate DNS requests?

**Comment by 9seconds** [comment]
It has a hardcoded list of ips. So, there is nothing to resolve for a proxy, hence no DNS queries are made
