### ISSUE TITLE
make ubuntu 16.04

### ISSUE THREAD

**Issue by MrMstafa** [9seconds/mtg#43]
hello
How to install in ubuntu 16.04?

**Comment by 9seconds** [comment]
Hi. You can download a statically compiled binary from the releases or run it as a Docker container. Please check README, there is no any distro specific

**Comment by MrMstafa** [comment]
@9seconds
When compiled in the docker, there is an error in this section
COPY - From = 0 /go/src/github.com/9seconds/mtg/mtg/usr/ local / bin / mtg

This error is related to Dockerfile

**Comment by 9seconds** [comment]
Please check if your docker version is fresh enough to support [multi-staged builds](https://docs.docker.com/develop/develop-images/multistage-build/). In either way, you can always use precompiled binaries from releases.

Also, docker image is [published on dockerhub](https://hub.docker.com/r/nineseconds/mtg/) so usually you have no need to build it on your own.

**Comment by 9seconds** [comment]
I close this ticket. Feel free to reopen if it is still required
