### ISSUE TITLE
Not connected

### ISSUE THREAD

**Issue by lengyihan7** [9seconds/mtg#58]
log:

{
  "ipv4": {
    "tg_url": "tg://proxy?port=8946&secret=dd5524ee2e3a7015045f12934417b947f0&server=x.x.x.x",
    "tme_url": "https://t.me/proxy?port=8946&secret=dd5524ee2e3a7015045f12934417b947f0&server=x.x.x.x",
    "tg_qrcode": "https://api.qrserver.com/v1/create-qr-code?data=tg%3A%2F%2Fproxy%3Fport%3D8946%26secret%3Ddd5524ee2e3a7015045f12934417b947f0%26server%3Dx.x.x.x&format=svg&qzone=4",
    "tme_qrcode": "https://api.qrserver.com/v1/create-qr-code?data=tg%3A%2F%2Fproxy%3Fport%3D8946%26secret%3Ddd5524ee2e3a7015045f12934417b947f0%26server%3Dx.x.x.x&format=svg&qzone=4"
  },
  "ipv6": {
    "tg_url": "",
    "tme_url": "",
    "tg_qrcode": "",
    "tme_qrcode": ""
  },
  "secret_for_mtproxybot": "5524ee2e3a7015045f12934417b947f0"
}
{"level":"error","ts":1541425163.1271372,"logger":"main","msg":"Cannot initialize client connection","connection_id":"e6e5d5e4-bff4-4e9d-a494-524308aebd48","error":"Cannot extract frame: Cannot extract obfuscated header: read tcp x.x.x.x:8946->x.x.x.x:22870: i/o timeout","errorVerbose":"read tcp x.x.x.x:8946->x.x.x.x:22870: i/o timeout\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/obfuscated2/frame.go:87: Cannot extract obfuscated header\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/client/direct.go:36: Cannot extract frame"}
{"level":"error","ts":1541425163.77422,"logger":"main","msg":"Cannot initialize client connection","connection_id":"61db5fa5-50fc-4f6f-b261-347e5381df68","error":"Cannot extract frame: Cannot extract obfuscated header: read tcp x.x.x.x:8946->x.x.x.x:22879: i/o timeout","errorVerbose":"read tcp x.x.x.x:8946->x.x.x.x:22879: i/o timeout\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/obfuscated2/frame.go:87: Cannot extract obfuscated header\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/client/direct.go:36: Cannot extract frame"}
{"level":"error","ts":1541425163.7894843,"logger":"main","msg":"Cannot initialize client connection","connection_id":"5a8ab790-681f-4e6b-b8ff-02a844a6b4d0","error":"Cannot extract frame: Cannot extract obfuscated header: read tcp x.x.x.x:8946->x.x.x.x:22880: i/o timeout","errorVerbose":"read tcp x.x.x.x:8946->x.x.x.x:22880: i/o timeout\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/obfuscated2/frame.go:87: Cannot extract obfuscated header\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/client/direct.go:36: Cannot extract frame"}

What is wrong？how to fix it?

**Comment by 9seconds** [comment]
> Cannot extract obfuscated header
> read tcp x.x.x.x:8946->x.x.x.x:22879: i/o timeout

This usually implies that a client is able to establish a TCP connection but do not send expected 64 bytes of a handshake to the proxy. Could you please check that you set the type of proxy as MTPROTO in Telegram client? mtg is MTPROTO proxy, it does not support the SOCKS5 protocol.

If it does not help, would you mind to share some details on how you actually run and trying to connect to Telegram using mtg? Also, I do not see the logged configuration, please try to update to the latest version.

**Comment by lengyihan7** [comment]
It should be no problem to use. I have several servers and I deployed this program exactly the same. Everything else is used normally, and this is an error.The client uses other agents（mtg） are normal.So, I think there should be a flaw in the vps or the operating system itself, because this server uses a small service provider, I try to check the system myself, thank you.

**Comment by 9seconds** [comment]
If you find something, please share: I've seen a couple of problems before so having a good collection of issues which can happen on different VPSes looks quite appealing to me :)

**Comment by 9seconds** [comment]
I'm closing this issue now. Feel free to reopen any time.
