### ISSUE TITLE
error running

### ISSUE THREAD

**Issue by 0x9a** [9seconds/mtg#59]
hi matser 
how can i fix it?

root@0x9a:~/mtg# ./run-mtg.sh
Using default tag: latest
latest: Pulling from nineseconds/mtg
Digest: sha256:8d78d690a0aa139521db17140720946d21ce150d254b5c39cbea02c948dad6a0
Status: Image is up to date for nineseconds/mtg:latest
31a26a9b2ea6
222813751c4a91dcaa26cb00051f216b1fd40b915f1fcb4901d1c102874b916c
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"open /proc/sys/net/ipv4/tcp_rmem: no such file or directory\"": unknown.

**Comment by 0x9a** [comment]
i reinstall it:

root@0x9a:~# docker pull nineseconds/mtg:stable
stable: Pulling from nineseconds/mtg
64f7164e255a: Pull complete
e3931b8a8d06: Pull complete
Digest: sha256:20db899d83b4f6cae51b8389cc4695d8365d71aa7bb5a427c7e3c8559ce0eed4
Status: Downloaded newer image for nineseconds/mtg:stable
root@berbidvps:~# docker run --name mtg --restart=unless-stopped -p 3128:3128 -q 3129:3129 -d nineseconds/mtg:stable dd$(openssl rand -hex 16)
unknown shorthand flag: 'q' in -q
See 'docker run --help'.


how can fix it

**Comment by 9seconds** [comment]
Please remote -q flag. I have an error in README :/
