### ISSUE TITLE
can't run docker exec -ti mtg "anything"

### ISSUE THREAD

**Issue by aminvakil** [9seconds/mtg#61]
I read the Dockerfile and I know it's alpine but I can't even `docker exec -ti mtg cat` something or `docker exec -ti mtg apk add' something or run bash or anything.

What is preventing me from doing so?

**Comment by 9seconds** [comment]
This is not Alpine :) This is [scratch](https://github.com/9seconds/mtg/blob/master/Dockerfile#L26), so it literally has no linux inside. Binary works with linux syscalls directly, it has no bindings to libc whatsoever.

Would you mind to tell me your use case?

**Comment by aminvakil** [comment]
Curiosity!
Thanks
