### ISSUE TITLE
Enforce secure mode

### ISSUE THREAD

**Issue by rlex** [9seconds/mtg#63]
Seems like RKN now banning proxies based on protocol fingerprint.
Iran was fast at figuring it out: https://github.com/TelegramMessenger/MTProxy/issues/35 
Secure mode with random padding helps (at least for now)
Might be good idea to set secure mode by default and allow disabling it via ENV/config.

**Comment by L11R** [comment]
There is an option already:
`But if you pass -s, then only clients with dd-secrets can connect.`
You cannot enforce clients to use secure mode.

**Comment by rlex** [comment]
My point was to disable old (non-secure) mode by default. Alot of people use mtproto proxies from containers and use whatever it outputs without any configuration (except secret key)
Just an IMHO, of course, but this might help if providers actually started to use DPI to ban proxies faster (like that case with metro wifi and socks proxies)

**Comment by L11R** [comment]
I guess it's okay to just fix README and add some disclaimer, but it shouldn't be default behavior.

**Comment by 9seconds** [comment]
A lot of installation I know are private ones which were created before dd-secrets and it is almost impossible to tell clients to change anything in that regard, this is a reason why it is not by default. Check this out: https://github.com/9seconds/mtg/issues/49 like an illustration :)

Could you please tell me how should I update README?

**Comment by L11R** [comment]
I guess we should add information about RKN that is currently blocking every MTProto Proxy after few days even without knowing your secret in fully private use. Seems like they start to scan traffic with DPI. So we should recommend people to use secure-only mode only to avoid IP block.

**Comment by 9seconds** [comment]
I've updated README. If you have some better words, feel free to open this ticket :)
