### ISSUE TITLE
Не подключается клиент при добавлении префикса dd

### ISSUE THREAD

**Issue by Ingiboy** [9seconds/mtg#64]
Добрый день!

mtg запущен вот так:
docker run --name mtg --restart=unless-stopped -p 8443:3128 -p 127.0.0.1:3129:3129 -d nineseconds/mtg -a 8443 <pass_here>

При добавлении в клиент префикса dd к ключу, клиент перестает соединяться с прокси. В чем может быть дело? Промежуточных прокси нет. Клиенты десктоп и мобильный, версии последние.

Согласно ридми это вррде бы(?) должно работать штатно.

**Comment by Ingiboy** [comment]
Да, dd я добавляю только на клиенте, на сервере, в указанной мной строке запуска, в качестве секрета указан 32-символьный ключ, к которому на клиенте.

Собственно, потому и вопрос - сложностей никаких ридми не демонстрирует, но не работает стабильно

**Comment by Ingiboy** [comment]
Да, dd я добавляю только на клиенте, на сервере, в указанной мной строке запуска, в качестве секрета указан 32-символьный ключ, к которому на клиенте.

Собственно, потому и вопрос - сложностей никаких ридми не демонстрирует, но не работает стабильно

**Comment by Ingiboy** [comment]
Да, mtg тоже последний.

**Comment by L11R** [comment]
Похоже на сервере тоже проверка на уровне `dd` в секрете. Попробуйте добавить. Возможно у меня как раз старая версия, где эта проверка выглядела иначе (посмотрел свой старый форк, там проще).
https://github.com/9seconds/mtg/blob/16558a7c551b3efcfd4cbf199536a1f8f2fd66f2/config/config.go#L126

**Comment by 9seconds** [comment]
Ну да, все должно работать. Давайте по шагам, как и что запускаете? Вот я только что проверил, и получил такое:

```console
root@localhost:~# echo dd$(openssl rand -hex 16)
dd0ccbe873713dab873795e211634d0b2d
root@localhost:~# sudo docker run -it -p 2000:3128 nineseconds/mtg --public-ipv4-port=2000 ddf68603805e65898c7583b14520efc6cd
{
  "ipv4": {
    "tg_url": "tg://proxy?port=2000&secret=ddf68603805e65898c7583b14520efc6cd&server=XXX.XXX.XXX.XXX",
    "tme_url": "https://t.me/proxy?port=2000&secret=ddf68603805e65898c7583b14520efc6cd&server=XXX.XXX.XXX.XXX",
    "tg_qrcode": "https://api.qrserver.com/v1/create-qr-code?data=tg%3A%2F%2Fproxy%3Fport%3D2000%26secret%3Dddf68603805e65898c7583b14520efc6cd%26server%3DXXX.XXX.XXX.XXX&format=svg&qzone=4",
    "tme_qrcode": "https://api.qrserver.com/v1/create-qr-code?data=tg%3A%2F%2Fproxy%3Fport%3D2000%26secret%3Dddf68603805e65898c7583b14520efc6cd%26server%3DXXX.XXX.XXX.XXX&format=svg&qzone=4"
  },
  "ipv6": {
    "tg_url": "",
    "tme_url": "",
    "tg_qrcode": "",
    "tme_qrcode": ""
  },
  "secret_for_mtproxybot": "f68603805e65898c7583b14520efc6cd"
}
```

После этого беру прямо ссылки из вывода тула, и работает. Ну, либо сам добавляю

**Comment by Ingiboy** [comment]
Я ориентировался на этот кусок мануала:

Now going back to the secure mode: if you do not pass -s flag to the mtg, then it checks what mode is requested by the client. If the client uses plain secret, without dd prefix, then proxy falls back to the original behavior and do not play with paddings. If dd-secret is used and client demands this mode, then proxy start to add that random noise to the packets. But if you pass -s, then only clients with dd-secrets can connect.
 
Видимо, неправильно понял.

Логика такая: если серверу скормить секрет с dd, но не ставить ключ -s при запуске, то клиенты могут себе прописать секрет как с dd, так и без него. 

Если же серверу даден секрет без dd, то он железно будет работать без повышенной секретности, и добавление dd _только_ на клиенте приведет к невозможности соединения.

Верно?

**Comment by Ingiboy** [comment]
Понятно. Я предполагал, что уровень секурности выставляется клиентом: серверу дается ключ без `dd`, а клиент волен сам добавлять `dd` на своей стороне. А тут выяснилось, что серверу нужен `dd` обязательно, чтобы на клиенте была возможность использовать и простой, и секурный режим.

**Comment by Ingiboy** [comment]
Ну, по крайней мере у меня не заработало, пока `dd` не был добавлен в секрету на сервере

**Comment by Ingiboy** [comment]
В любом случае спасибо за помощь, разобрался)

**Comment by 9seconds** [comment]
Надо бы мне пересмотреть настройки, раз такой конфуз случается. Это явно проблема дизайна)
