### ISSUE TITLE
adtag problems

### ISSUE THREAD

**Issue by snetesa** [9seconds/mtg#65]
Добрый день!
При попытке запуска в докере с указанием adtag в лог валится ошибка:
`{"level":"error","ts":1549551762.0736535,"logger":"main","msg":"Cannot initialize server connection","connection_id":"0da214ef-e6db-40d9-a66c-f22152d2f272","error":"Cannot handshake telegram: Cannot read RPC handshake response: Cannot read frame padding: Cannot read from socket: EOF","errorVerbose":"EOF\ngithub.com/9seconds/mtg/wrappers/blockcipher.go:37: Cannot read from socket\ngithub.com/9seconds/mtg/wrappers/mtproto_frame.go:52: Cannot read frame padding\ngithub.com/9seconds/mtg/telegram/middle.go:100: Cannot read RPC handshake response\ngithub.com/9seconds/mtg/proxy/proxy.go:118: Cannot handshake telegram"}`
Клиенты при этом не подключаются. 
Запускать пытался вот так:
`docker run --name mtg-latest --restart=unless-stopped -p 8888:3128 -p 3129:3129 -d nineseconds/mtg:latest -s <ddsecret> <adtag>`
При запуске без adtag все прекрасно работает. Пробовал на stable и latest. 
Может быть опять какие-то изменения в API, как этом [issue](https://github.com/9seconds/mtg/issues/36)?

**Comment by someone99119** [comment]
yup , i have same problem .
it happens even when it's not with docker .

**Comment by 9seconds** [comment]
Cannot handshake telegram - please check that time on your machine does not drift, this is important for "adtag" protocol since Telegram checks it on the server side. If you have log messages like "NTP time drift", this is the problem.

**Comment by someone99119** [comment]
> Cannot handshake telegram - please check that time on your machine does not drift, this is important for "adtag" protocol since Telegram checks it on the server side. If you have log messages like "NTP time drift", this is the problem.


in my case There is NO ERROR about time drift !

level":"info","ts":1549872711.2822554,"msg":"Use middle proxy connection to Telegram"}
{"level":"info","ts":1549872712.0225432,"msg":"Telegram middle proxy data has been updated"}
{"level":"info","ts":1549872712.6344993,"logger":"main","msg":"Client connected","connection_id":"5407c897-2ed7-482a-a8db-2579c4588743","addr":"ip:51576"}
{"level":"error","ts":1549872712.6389215,"logger":"main","msg":"Cannot initialize client connection","connection_id":"5407c897-2ed7-482a-a8db-2579c4588743","error":"Cannot parse obfuscated frame: Unknown protocol: Unknown handshake protocol","errorVerbose":"/home/vagrant/safe/go/src/github.com/9seconds/mtg/mtproto/connection_options.go:86: Unknown handshake protocol\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/obfuscated2/obfuscated2.go:40: Unknown protocol\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/client/direct.go:43: Cannot parse obfuscated frame"}
{"level":"info","ts":1549872713.1616642,"logger":"main","msg":"Client connected","connection_id":"8435b841-2a99-423f-83b8-ef2ee62c84fc","addr":"ip:51578"}
{"level":"error","ts":1549872713.1711507,"logger":"main","msg":"Cannot initialize client connection","connection_id":"8435b841-2a99-423f-83b8-ef2ee62c84fc","error":"Cannot parse obfuscated frame: Unknown protocol: Unknown handshake protocol","errorVerbose":"/home/vagrant/safe/go/src/github.com/9seconds/mtg/mtproto/connection_options.go:86: Unknown handshake protocol\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/obfuscated2/obfuscated2.go:40: Unknown protocol\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/client/direct.go:43: Cannot parse obfuscated frame"}
{"level":"info","ts":1549872713.8796258,"logger":"main","msg":"Client connected","connection_id":"fba38be9-2ebb-4001-a1d9-55cf46a75c4f","addr":"ip:51580"}
{"level":"error","ts":1549872713.880114,"logger":"main","msg":"Cannot initialize client connection","connection_id":"fba38be9-2ebb-4001-a1d9-55cf46a75c4f","error":"Cannot parse obfuscated frame: Unknown protocol: Unknown handshake protocol","errorVerbose":"/home/vagrant/safe/go/src/github.com/9seconds/mtg/mtproto/connection_options.go:86: Unknown handshake protocol\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/obfuscated2/obfuscated2.go:40: Unknown protocol\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/client/direct.go:43: Cannot parse obfuscated frame"}
{"level":"info","ts":1549872714.4234707,"logger":"main","msg":"Client connected","connection_id":"6d367d30-e89a-47be-8775-b7b233d69a35","addr":"ip:51582"}
{"level":"error","ts":1549872714.4267185,"logger":"main","msg":"Cannot initialize client connection","connection_id":"6d367d30-e89a-47be-8775-b7b233d69a35","error":"Cannot parse obfuscated frame: Unknown protocol: Unknown handshake protocol","errorVerbose":"/home/vagrant/safe/go/src/github.com/9seconds/mtg/mtproto/connection_options.go:86: Unknown handshake protocol\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/obfuscated2/obfuscated2.go:40: Unknown protocol\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/client/direct.go:43: Cannot parse obfuscated frame"}

**Comment by 9seconds** [comment]
@someone99119 you have another problem: mismatch of the secret. The secret on client and server are different.

**Comment by someone99119** [comment]
> @someone99119 you have another problem: mismatch of the secret. The secret on client and server are different.

Its working before adding ad-tag .
it detects ad-tag properly but user can't connect

**Comment by 9seconds** [comment]
The user cannot connect because proxy cannot decrypt its packets. It happens because of the different secrets on both user and client. At that moment connection to Telegram is not established yet, proxy failed to decrypt user traffic.

**Comment by snetesa** [comment]
> Cannot handshake telegram - please check that time on your machine does not drift, this is important for "adtag" protocol since Telegram checks it on the server side. If you have log messages like "NTP time drift", this is the problem.

I've checked it out. System time is synced by NTP and there's not any NTP errors in the log. It works perfectly without ad-tag with the same secret.

**Comment by someone99119** [comment]
> The user cannot connect because proxy cannot decrypt its packets. It happens because of the different secrets on both user and client. At that moment connection to Telegram is not established yet, proxy failed to decrypt user traffic.

Thanks .
i was adding ad-tag first parameter and secret after it ...
after adding secret and ad-tag after that everything is ok .
sorry !

**Comment by 9seconds** [comment]
@snetesa could you please share full log somewhere on pastebin?

**Comment by 9seconds** [comment]
@someone99119 great it works now :)

**Comment by snetesa** [comment]
Sure: https://pastebin.com/iiXTNj9i
There is one repeating error it the log. IP and secret were changed to "My_IP_here" and "secret123" respectively. The proxy's located behind NAT - can it be the reason?

**Comment by 9seconds** [comment]
This is quite weird, it seems that telegram aborts connection at the very beginning when proxy sends _predefined_ request. Can you please check if you have connectivity to telegram hosts from these nodes (`curl https://core.telegram.org/getProxyConfig` and try to access host/port pairs from the response). If the issue still exists, I would like to ask you to run mtg without docker (if you run docker) with debug mode.

**Comment by 9seconds** [comment]
@snetesa do you have any news?
