### ISSUE TITLE
IP адрес

### ISSUE THREAD

**Issue by Azat868** [9seconds/mtg#66]
Добрый день
Возможно ли чтобы ip адрес клиента не отправлялся на сервер телеграм. Чтобы все клиенты представлялись ip адресом сервера mtprotoproxy. Если не правильно выразился пожалуйста поправьте.

**Comment by 9seconds** [comment]
Здравствуйте. К сожалению, протокол такого не поддерживает. Насколько я понимаю (я не разработчик Телеграма, только догадки), это необходимо хотя бы потому, что сервер должен знать, кому нужно послать сообщение. Прокси не имеет возможности "подсмотреть" в пакет.
