### ISSUE TITLE
Multi-secrets mode

### ISSUE THREAD

**Issue by kibermaster** [9seconds/mtg#67]
I think it's a good idea to implement a multi-secrets mode. Although you have an opinion that one secret is enough there are a lot of situations when such mode would be useful. For example: private proxy for corporate use, each department has individual secret so if a secret leaked out, it's easier to change it for several users than for all corporation. This mode should be optional and must be disabled by default.

**Comment by 9seconds** [comment]
You can find a multi-secret in other implementations. I share another vision: I see no point of having multiple secrets. What you will achieve there?

1. If you are trying to hide from internet censorship, it makes no sense to rotate secrets. IP is banned and all users lose their access
2. If you leak the secret, you _do not have any security breach_. Proxy just accesses Telegram. All you will have is that more users will be able to access the Telegram.

I share the same vision as shadowsocks project: proxy should be easily deployable, disposable with almost no configuration. If the proxy is banned, this is fine: let's just deploy another proxy.
