### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by kibermaster** [9seconds/mtg#68]
I try to build this way: 

go get -v -u github.com/mtProtoProxy/mtg

At the end I get this:

go/src/src/github.com/mtProtoProxy/mtg/main.go:144:31: not enough arguments in call to config.NewConfig
        have (bool, bool, uint32, uint32, net.IP, net.IP, net.IP, net.IP, uint16, uint16, uint16, uint16, uint16, string, string, string, string, map[string]string, []byte, []byte)
        want (bool, bool, uint32, uint32, net.IP, net.IP, net.IP, net.IP, uint16, uint16, uint16, uint16, uint16, string, string, string, string, map[string]string, string, bool, []byte, []byte)
go/src/src/github.com/mtProtoProxy/mtg/main.go:191:12: undefined: stats.Start

===

Am I doing something wrong or there is a bug?

SYS: Centos 7

**Comment by 9seconds** [comment]
Hi. I do not support the mentioned repository. Please check readme to get a list of possible options on getting this proxy.
