### ISSUE TITLE
"Cannot pump sockets" in log

### ISSUE THREAD

**Issue by BorBorisych** [9seconds/mtg#69]
Hello!
Works fine, but the stderr log is full of messages "Cannot pump sockets", "Cannot read stream ciphered data". 
Run it under CentOS 7 without docker in secret only mode at VPS based in England (log in verbose mode). Tried both to download ready to run file at "Releases" and build it ("Master" branch) - issue exists in both cases.
---
{"level":"warn","ts":1551001510.551488,"logger":"conn.stream-cipher","msg":"Cannot pump sockets","connection_id":"60e8701b-0070-4acc-8d63-08c4084d7fd1","local_address":"185.133.192.131:2309","remote_address":"37.204.77.54:38868","purpose":"client","faked_local_addr":"185.133.192.131:2309","error":"Cannot read stream ciphered data: read tcp 185.133.192.131:2309->37.204.77.54:38868: i/o timeout","errorVerbose":"read tcp 185.133.192.131:2309->37.204.77.54:38868: i/o timeout\n/home/mtg_proto/mtg-master/wrappers/streamcipher.go:24: Cannot read stream ciphered data"}
{"level":"warn","ts":1551001510.5516129,"logger":"conn.stream-cipher","msg":"Cannot pump sockets","connection_id":"60e8701b-0070-4acc-8d63-08c4084d7fd1","local_address":"[2a06:8ec0:3::1:12d7]:22251","remote_address":"[2001:67c:4e8:f002::a]:443","purpose":"telegram","faked_local_addr":"[2a06:8ec0:3::1:12d7]:22251"
,"error":"Cannot read stream ciphered data: read tcp [2a06:8ec0:3::1:12d7]:22251->[2001:67c:4e8:f002::a]:443: use of closed network connection","errorVerbose
":"read tcp [2a06:8ec0:3::1:12d7]:22251->[2001:67c:4e8:f002::a]:443: use of closed network connection\n/home/mtg_proto/mtg-master/wrappers/streamcipher.go:24: Cannot read stream ciphered data"}
{"level":"warn","ts":1551001634.9258738,"logger":"conn.stream-cipher","msg":"Cannot pump sockets","connection_id":"b7cddd0d-371a-4fc8-a2e9-f7f997fe7bc5","local_address":"185.133.192.131:2309","remote_address":"37.204.77.54:38886","purpose":"client","faked_local_addr":"185.133.192.131:2309","error":"Cannot read stream ciphered data: read tcp 185.133.192.131:2309->37.204.77.54:38886: i/o timeout","errorVerbose":"read tcp 185.133.192.131:2309->37.204.77.54:38886: i/o timeout\n/home/mtg_proto/mtg-master/wrappers/streamcipher.go:24: Cannot read stream ciphered data"}
{"level":"warn","ts":1551001634.9259834,"logger":"conn.stream-cipher","msg":"Cannot pump sockets","connection_id":"b7cddd0d-371a-4fc8-a2e9-f7f997fe7bc5","local_address":"[2a06:8ec0:3::1:12d7]:26165","remote_address":"[2001:67c:4e8:f002::a]:443","purpose":"telegram","faked_local_addr":"[2a06:8ec0:3::1:12d7]:26165"
,"error":"Cannot read stream ciphered data: read tcp [2a06:8ec0:3::1:12d7]:26165->[2001:67c:4e8:f002::a]:443: use of closed network connection","errorVerbose
":"read tcp [2a06:8ec0:3::1:12d7]:26165->[2001:67c:4e8:f002::a]:443: use of closed network connection\n/home/mtg_proto/mtg-master/wrappers/streamcipher.go:24: Cannot read stream ciphered data"}
{"level":"warn","ts":1551001759.0788708,"logger":"conn.stream-cipher","msg":"Cannot pump sockets","connection_id":"04f00825-beaa-4b48-882a-fa3577ea412c","local_address":"185.133.192.131:2309","remote_address":"37.204.77.54:38894","purpose":"client","faked_local_addr":"185.133.192.131:2309","error":"Cannot read stream ciphered data: read tcp 185.133.192.131:2309->37.204.77.54:38894: i/o timeout","errorVerbose":"read tcp 185.133.192.131:2309->37.204.77.54:38894: i/o timeout\n/home/mtg_proto/mtg-master/wrappers/streamcipher.go:24: Cannot read stream ciphered data"}

**Comment by 9seconds** [comment]
The reason is that connection to the client is closed but proxy still tries to read from the socket. I expect this is related to preliminary closing of idle connection but not completely sure :/ It is [2 minutes now](https://github.com/9seconds/mtg/blob/master/wrappers/conn.go#L36-L39).

I need to make this configurable

**Comment by BorBorisych** [comment]
Thank you for quick reply! Will try to decrease both timeouts - set them as low as 1 minute for example, rebuild the binary and check the log.

**Comment by BorBorisych** [comment]
Well, did some experiments now. Tried to tune both (read/write) timeouts - from 1 second to 30 minutes: messages "Cannot pump sockets" still exists in log anyway. And it seems the default value (2 minutes) was the among the best :) - the number of warnings in log seems to be the lowest being compared with other timeout values.
If you need I can make some other experiments to help you fix the issue - make changes in sources, rebuild, etc.

**Comment by 9seconds** [comment]
They exist, yes. Actually, this is not a huge problem per se: it means that another side of "duplex" was aborted due to operation deadline. I need to think, how to avoid excessive, possibly misleading logging :/

**Comment by BorBorisych** [comment]
Thank you for your comments.
