### ISSUE TITLE
рандомизация в хендшейке

### ISSUE THREAD

**Issue by f242** [9seconds/mtg#74]
тут в соседней репе запилили рандомизацию в хендшейке, если я не обосрался и правильно понял) хотелось бы и тут такое видеть, очень уж прокся хорошая https://github.com/alexbers/mtprotoproxy/commit/4cae6290b9529485125366771005460309a835b5

**Comment by uprt** [comment]
Плюс еще второй патч  [alexbers/mtprotoproxy@ `f55ae68`](https://github.com/alexbers/mtprotoproxy/commit/f55ae68092b4f07e247baa18ad35b014380a9eeb), который дополняет первый.

**Comment by 9seconds** [comment]
Это не совсем про рандомизацию, скорее про обход replay-аттак. В русскоговорящих странах это пока что не очень актуально, но в Иране и Китае уже начали практиковать вычисление проксей этим методом.

Я скоро запилю нечто подобное, просто пока что банально нет времени

**Comment by 9seconds** [comment]
Базовая штука сделана. Я это неделю пока на мастере потестирую, потом соберу стабильную ветку.
