### ISSUE TITLE
обновление с сохранением секрета

### ISSUE THREAD

**Issue by f242** [9seconds/mtg#78]
а как правильно докер обновлять, я каждый раз секрет везде переставляю, наверно можно как-то по феншую делать, а то если несколько устройств менять на каждом утомительно
запускаю я его в secure mode на 443 порту вот так:
`docker run --name mtg --restart=always -p 443:443 -p 3129:3129 -d nineseconds/mtg:latest dd$(openssl rand -hex 16) --secure-only --public-ipv4 ххх.xxx.xxx.xxх --bind-port 443`
где ххх - ip адрес vps'ки
в документации этот вопрос вроде не освещён

**Comment by 9seconds** [comment]
Оу, да, это болезненные обновления :) Я через этот скрипт сам пускаю, он прямо в репозитории лежит. Дополнительные настройки нужно в него прокинуть, но, надеюсь, там все довольно понятно: https://github.com/9seconds/mtg/blob/master/run-mtg.sh

**Comment by 9seconds** [comment]
Там идея в том, что секрет генерируется один раз и сохраняется в файл. Если этот файл есть, то секрет берется оттуда же
