### ISSUE TITLE
Process dead

### ISSUE THREAD

**Issue by ChenSee** [9seconds/mtg#79]
![image](https://user-images.githubusercontent.com/11918919/57505948-eb99ef00-732c-11e9-87ac-440ebf553c41.png)
Centos 6.10
mtg -p 443 -b 0.0.0.0 ...
The process always dies, for no reason, and it will be like this in a while.

**Comment by ChenSee** [comment]
![image](https://user-images.githubusercontent.com/11918919/57577525-8fa9a480-74ab-11e9-9e9c-818e09d9c8e5.png)

**Comment by 9seconds** [comment]
I see that goroutine panics on executing some syscall related to epoll but unfortunately, this is all I see. Could you please upload your logs on gist or somewhere to Pastebin? I need to see full logs.

**Comment by ChenSee** [comment]
thank you,that's no problem.
