### ISSUE TITLE
Multiple ports

### ISSUE THREAD

**Issue by SimWhite** [9seconds/mtg#81]
Are there any ways to listen on multiple ports? If not, than let is be feature request.

**Comment by 9seconds** [comment]
Could you please elaborate on the use case? Right now you can run multiple proxies and bind them to the different ports.

**Comment by SimWhite** [comment]
Some providers block some ports. The use case to open different ports for users which they can use. Also multiple proxies → multiple process → more resources.

**Comment by 9seconds** [comment]
Ah, I see. Usually, it is a better idea to move such logic out of the application and [use iptables or other firewalls to perform such routing](https://www.cyberciti.biz/faq/linux-port-redirection-with-iptables/).
