### ISSUE TITLE
Cannot initialize client connection

### ISSUE THREAD

**Issue by SimWhite** [9seconds/mtg#82]
Sometimes I get in logs:
```
{"level":"error","ts":1558105435.3307085,"logger":"main","msg":"Cannot initialize client connection","connection_id":"f4cb4c45-xxxx-xxxx-xxxx-xxxx6eccxxxx","error":"Cannot extract frame: Cannot extract obfuscated header: read tcp xx.xx.xx.xx:8443->88.232.168.38:19552: i/o timeout","errorVerbose":"read tcp xx.xx.xx.xx:8443->88.232.168.38:19552: i/o timeout\n/root/mtg/obfuscated2/frame.go:87: Cannot extract obfuscated header\n/root/mtg/client/direct.go:38: Cannot extract frame"}
```
Also the interesting thing that 88.232.168.38 IP is the TurkTelekom. But I haven't any connections with Turkish networks. Maybe these are DPI probes from the Turkey?

UPD: Another one error from the log without any IP's:

```
{"level":"error","ts":1558105659.805035,"logger":"main","msg":"Cannot initialize client connection","connection_id":"d4fa3c04-xxxx-xxxx-xxxx-xxxx6b3bxxxx","error":"Cannot extract frame: Cannot extract obfuscated header: EOF","errorVerbose":"EOF\n/root/mtg/obfuscated2/frame.go:87: Cannot extract obfuscated header\n/root/mtg/client/direct.go:38: Cannot extract frame"}
```

**Comment by 9seconds** [comment]
This error means that someone has opened tcp connection but did not send correct handshake bytes (0 bytes or just a couple of them). Proxy has closed this connection by timeout.

This can happen for various reasons. For example, someone from this IP address used Nmap to scan your host for an open port. If you want to prevent this connection, you can block them with iptables, ufw or any other firewall.

**Comment by SimWhite** [comment]
But the second error example was without IP and the connection ID was different from others in logs. What is the reason could be?

**Comment by 9seconds** [comment]
Another connection most probably. ConnectionID is generated for every TCP connection. I mean, I checked sources where this error happened. We try to read the first 64 bytes from the network connection and fail by timeout (1st case) or because remote machine send TCP FIN.

**Comment by bao3** [comment]
Hey @9seconds ,

I got the same issue ,but it would run well without ADtag. I reopen this issue, because I get the debug info for you ,hope it would help use to fix the bug.

# Some Tips

>f1348c31c589","local_address":"$MyServerIP:10010","remote_address":"$MyPCIP:59379","purpose":"client","faked_local_addr":"$MyPublicIP:10010"}

`$MyServerIP`: My Server is behind a Router , My Server IP is 172.16.0.0/16 
`$MyPCIP`: My telegram running on my PC, the Server and my PC  is in the same LAN, IP is also 172.16.0.0/16
`$MyPublicIP`: My Router WAN IP ,it's IPv4 

# The Debug Info

>{"level":"debug","ts":1561734529.2192397,"logger":"conn","msg":"Close connection","connection_id":"dc043fc9-7b43-47d5-92e4-f1348c31c589","local_address":"$MyServerIP:10010","remote_address":"$MyPCIP:59379","purpose":"client","faked_local_addr":"$MyPublicIP:10010"}
>{"level":"debug","ts":1561734529.2277925,"logger":"conn","msg":"Read from stream","connection_id":"848f1532-20e7-46db-8e05-f15f46dfb26d","local_address":"$MyServerIP:26598","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26598","bytes":0,"error":"EOF"}
>{"level":"debug","ts":1561734529.2279105,"logger":"conn","msg":"Close connection","connection_id":"848f1532-20e7-46db-8e05-f15f46dfb26d","local_address":"$MyServerIP:26598","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26598"}
>{"level":"error","ts":1561734529.2280586,"logger":"main","msg":"Cannot initialize server connection","connection_id":"848f1532-20e7-46db-8e05-f15f46dfb26d","error":"Cannot handshake telegram: Cannot read RPC handshake response: Cannot read frame padding: Cannot read from socket: EOF","errorVerbose":"EOF\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/wrappers/blockcipher.go:37: Cannot read from socket\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/wrappers/mtproto_frame.go:52: Cannot read frame padding\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/telegram/middle.go:100: Cannot read RPC handshake response\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/proxy/proxy.go:118: Cannot handshake telegram"}
>{"level":"debug","ts":1561734529.2281423,"logger":"conn","msg":"Close connection","connection_id":"848f1532-20e7-46db-8e05-f15f46dfb26d","local_address":"$MyServerIP:10010","remote_address":"$MyPCIP:59380","purpose":"client","faked_local_addr":"$MyPublicIP:10010"}
>{"level":"info","ts":1561734530.237792,"logger":"main","msg":"Client connected","connection_id":"b5a22f02-a7ef-4445-a078-776342de654e","addr":"$MyPCIP:59383"}
>{"level":"info","ts":1561734530.238239,"logger":"conn.stream-cipher","msg":"Client connection initialized","connection_id":"b5a22f02-a7ef-4445-a078-776342de654e","local_address":"$MyServerIP:10010","remote_address":"$MyPCIP:59383","purpose":"client","faked_local_addr":"$MyPublicIP:10010"}
>{"level":"info","ts":1561734530.2389033,"logger":"main","msg":"Client connected","connection_id":"d150eea7-2b2a-4c6b-8b93-b2f7d8d67b9d","addr":"$MyPCIP:59384"}
>{"level":"info","ts":1561734530.2394247,"logger":"conn.stream-cipher","msg":"Client connection initialized","connection_id":"d150eea7-2b2a-4c6b-8b93-b2f7d8d67b9d","local_address":"$MyServerIP:10010","remote_address":"$MyPCIP:59384","purpose":"client","faked_local_addr":"$MyPublicIP:10010"}
>{"level":"info","ts":1561734530.2398982,"logger":"main","msg":"Client connected","connection_id":"e1486090-dd55-4bfb-834f-f33f8418a02c","addr":"$MyPCIP:59382"}
>{"level":"info","ts":1561734530.2402203,"logger":"conn.stream-cipher","msg":"Client connection initialized","connection_id":"e1486090-dd55-4bfb-834f-f33f8418a02c","local_address":"$MyServerIP:10010","remote_address":"$MyPCIP:59382","purpose":"client","faked_local_addr":"$MyPublicIP:10010"}
>{"level":"debug","ts":1561734530.240977,"logger":"conn.mtproto-frame","msg":"Write MTProto frame","connection_id":"b5a22f02-a7ef-4445-a078-776342de654e","local_address":"$MyServerIP:26599","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26599","length":32,"sequence_number":-2,"crc32":235454558,"frame_length":48}
>{"level":"debug","ts":1561734530.2411427,"logger":"conn","msg":"Write to stream","connection_id":"b5a22f02-a7ef-4445-a078-776342de654e","local_address":"$MyServerIP:26599","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26599","bytes":48,"error":null}
>{"level":"debug","ts":1561734530.2414606,"logger":"conn.mtproto-frame","msg":"Write MTProto frame","connection_id":"d150eea7-2b2a-4c6b-8b93-b2f7d8d67b9d","local_address":"$MyServerIP:26600","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26600","length":32,"sequence_number":-2,"crc32":3081505464,"frame_length":48}
>{"level":"debug","ts":1561734530.2417574,"logger":"conn","msg":"Write to stream","connection_id":"d150eea7-2b2a-4c6b-8b93-b2f7d8d67b9d","local_address":"$MyServerIP:26600","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26600","bytes":48,"error":null}
>{"level":"debug","ts":1561734530.2421224,"logger":"conn.mtproto-frame","msg":"Write MTProto frame","connection_id":"e1486090-dd55-4bfb-834f-f33f8418a02c","local_address":"$MyServerIP:26601","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26601","length":32,"sequence_number":-2,"crc32":3837860153,"frame_length":48}
>{"level":"debug","ts":1561734530.242271,"logger":"conn","msg":"Write to stream","connection_id":"e1486090-dd55-4bfb-834f-f33f8418a02c","local_address":"$MyServerIP:26601","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26601","bytes":48,"error":null}
>{"level":"info","ts":1561734530.5284703,"logger":"main","msg":"Client connected","connection_id":"f182d375-f7ad-41b6-bb77-66f66f911f0f","addr":"$MyPCIP:59385"}
>{"level":"info","ts":1561734530.5292354,"logger":"conn.stream-cipher","msg":"Client connection initialized","connection_id":"f182d375-f7ad-41b6-bb77-66f66f911f0f","local_address":"$MyServerIP:10010","remote_address":"$MyPCIP:59385","purpose":"client","faked_local_addr":"$MyPublicIP:10010"}
>{"level":"debug","ts":1561734530.5300255,"logger":"conn.mtproto-frame","msg":"Write MTProto frame","connection_id":"f182d375-f7ad-41b6-bb77-66f66f911f0f","local_address":"$MyServerIP:26602","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26602","length":32,"sequence_number":-2,"crc32":3567794734,"frame_length":48}
>{"level":"debug","ts":1561734530.53013,"logger":"conn","msg":"Write to stream","connection_id":"f182d375-f7ad-41b6-bb77-66f66f911f0f","local_address":"$MyServerIP:26602","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26602","bytes":48,"error":null}
>{"level":"info","ts":1561734530.5782905,"logger":"main","msg":"Client connected","connection_id":"d3c1d171-b1a5-42bc-88e7-72c44f1f3bc0","addr":"$MyPCIP:59386"}
>{"level":"info","ts":1561734530.5806406,"logger":"conn.stream-cipher","msg":"Client connection initialized","connection_id":"d3c1d171-b1a5-42bc-88e7-72c44f1f3bc0","local_address":"$MyServerIP:10010","remote_address":"$MyPCIP:59386","purpose":"client","faked_local_addr":"$MyPublicIP:10010"}
>{"level":"debug","ts":1561734530.5814245,"logger":"conn.mtproto-frame","msg":"Write MTProto frame","connection_id":"d3c1d171-b1a5-42bc-88e7-72c44f1f3bc0","local_address":"$MyServerIP:26603","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26603","length":32,"sequence_number":-2,"crc32":4054107343,"frame_length":48}
>{"level":"debug","ts":1561734530.5815256,"logger":"conn","msg":"Write to stream","connection_id":"d3c1d171-b1a5-42bc-88e7-72c44f1f3bc0","local_address":"$MyServerIP:26603","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26603","bytes":48,"error":null}
>{"level":"debug","ts":1561734530.6324153,"logger":"conn","msg":"Read from stream","connection_id":"d150eea7-2b2a-4c6b-8b93-b2f7d8d67b9d","local_address":"$MyServerIP:26600","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26600","bytes":4,"error":null}
>{"level":"debug","ts":1561734530.6325052,"logger":"conn.mtproto-frame","msg":"Read MTProto frame","connection_id":"d150eea7-2b2a-4c6b-8b93-b2f7d8d67b9d","local_address":"$MyServerIP:26600","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26600","messageLength":44,"sequence_number":-2}
>{"level":"debug","ts":1561734530.6325932,"logger":"conn","msg":"Read from stream","connection_id":"d150eea7-2b2a-4c6b-8b93-b2f7d8d67b9d","local_address":"$MyServerIP:26600","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26600","bytes":36,"error":null}
>{"level":"debug","ts":1561734530.6326737,"logger":"conn","msg":"Read from stream","connection_id":"d150eea7-2b2a-4c6b-8b93-b2f7d8d67b9d","local_address":"$MyServerIP:26600","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26600","bytes":4,"error":null}
>{"level":"debug","ts":1561734530.6327016,"logger":"conn.mtproto-frame","msg":"Read MTProto frame","connection_id":"d150eea7-2b2a-4c6b-8b93-b2f7d8d67b9d","local_address":"$MyServerIP:26600","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26600","messageLength":44,"sequence_number":-2,"dataLength":32,"checksum":2789451271}
>{"level":"debug","ts":1561734530.6327808,"logger":"conn.block-cipher.mtproto-frame","msg":"Write MTProto frame","connection_id":"d150eea7-2b2a-4c6b-8b93-b2f7d8d67b9d","local_address":"$MyServerIP:26600","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26600","length":32,"sequence_number":-1,"crc32":2166191618,"frame_length":48}
>{"level":"debug","ts":1561734530.6328874,"logger":"conn","msg":"Write to stream","connection_id":"d150eea7-2b2a-4c6b-8b93-b2f7d8d67b9d","local_address":"$MyServerIP:26600","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26600","bytes":48,"error":null}
>{"level":"debug","ts":1561734530.632974,"logger":"conn","msg":"Read from stream","connection_id":"b5a22f02-a7ef-4445-a078-776342de654e","local_address":"$MyServerIP:26599","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26599","bytes":4,"error":null}
>{"level":"debug","ts":1561734530.6330044,"logger":"conn.mtproto-frame","msg":"Read MTProto frame","connection_id":"b5a22f02-a7ef-4445-a078-776342de654e","local_address":"$MyServerIP:26599","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26599","messageLength":44,"sequence_number":-2}
>{"level":"debug","ts":1561734530.6330633,"logger":"conn","msg":"Read from stream","connection_id":"b5a22f02-a7ef-4445-a078-776342de654e","local_address":"$MyServerIP:26599","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26599","bytes":36,"error":null}
>{"level":"debug","ts":1561734530.6332548,"logger":"conn","msg":"Read from stream","connection_id":"b5a22f02-a7ef-4445-a078-776342de654e","local_address":"$MyServerIP:26599","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26599","bytes":4,"error":null}
>{"level":"debug","ts":1561734530.633285,"logger":"conn.mtproto-frame","msg":"Read MTProto frame","connection_id":"b5a22f02-a7ef-4445-a078-776342de654e","local_address":"$MyServerIP:26599","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26599","messageLength":44,"sequence_number":-2,"dataLength":32,"checksum":1950272182}
>{"level":"debug","ts":1561734530.6333895,"logger":"conn.block-cipher.mtproto-frame","msg":"Write MTProto frame","connection_id":"b5a22f02-a7ef-4445-a078-776342de654e","local_address":"$MyServerIP:26599","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26599","length":32,"sequence_number":-1,"crc32":2166191618,"frame_length":48}
>{"level":"debug","ts":1561734530.6335053,"logger":"conn","msg":"Write to stream","connection_id":"b5a22f02-a7ef-4445-a078-776342de654e","local_address":"$MyServerIP:26599","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26599","bytes":48,"error":null}
>{"level":"debug","ts":1561734530.6336012,"logger":"conn","msg":"Read from stream","connection_id":"e1486090-dd55-4bfb-834f-f33f8418a02c","local_address":"$MyServerIP:26601","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26601","bytes":4,"error":null}
>{"level":"debug","ts":1561734530.6336327,"logger":"conn.mtproto-frame","msg":"Read MTProto frame","connection_id":"e1486090-dd55-4bfb-834f-f33f8418a02c","local_address":"$MyServerIP:26601","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26601","messageLength":44,"sequence_number":-2}
>{"level":"debug","ts":1561734530.6336925,"logger":"conn","msg":"Read from stream","connection_id":"e1486090-dd55-4bfb-834f-f33f8418a02c","local_address":"$MyServerIP:26601","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26601","bytes":36,"error":null}
>{"level":"debug","ts":1561734530.6337616,"logger":"conn","msg":"Read from stream","connection_id":"e1486090-dd55-4bfb-834f-f33f8418a02c","local_address":"$MyServerIP:26601","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26601","bytes":4,"error":null}
>{"level":"debug","ts":1561734530.6337898,"logger":"conn.mtproto-frame","msg":"Read MTProto frame","connection_id":"e1486090-dd55-4bfb-834f-f33f8418a02c","local_address":"$MyServerIP:26601","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26601","messageLength":44,"sequence_number":-2,"dataLength":32,"checksum":1762908867}
>{"level":"debug","ts":1561734530.6338449,"logger":"conn.block-cipher.mtproto-frame","msg":"Write MTProto frame","connection_id":"e1486090-dd55-4bfb-834f-f33f8418a02c","local_address":"$MyServerIP:26601","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26601","length":32,"sequence_number":-1,"crc32":2166191618,"frame_length":48}
>{"level":"debug","ts":1561734530.633923,"logger":"conn","msg":"Write to stream","connection_id":"e1486090-dd55-4bfb-834f-f33f8418a02c","local_address":"$MyServerIP:26601","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26601","bytes":48,"error":null}
>{"level":"debug","ts":1561734530.8265731,"logger":"conn","msg":"Read from stream","connection_id":"d150eea7-2b2a-4c6b-8b93-b2f7d8d67b9d","local_address":"$MyServerIP:26600","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26600","bytes":0,"error":"EOF"}
>{"level":"debug","ts":1561734530.8267033,"logger":"conn","msg":"Close connection","connection_id":"d150eea7-2b2a-4c6b-8b93-b2f7d8d67b9d","local_address":"$MyServerIP:26600","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26600"}
>{"level":"error","ts":1561734530.8268242,"logger":"main","msg":"Cannot initialize server connection","connection_id":"d150eea7-2b2a-4c6b-8b93-b2f7d8d67b9d","error":"Cannot handshake telegram: Cannot read RPC handshake response: Cannot read frame padding: Cannot read from socket: EOF","errorVerbose":"EOF\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/wrappers/blockcipher.go:37: Cannot read from socket\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/wrappers/mtproto_frame.go:52: Cannot read frame padding\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/telegram/middle.go:100: Cannot read RPC handshake response\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/proxy/proxy.go:118: Cannot handshake telegram"}
>{"level":"debug","ts":1561734530.8269107,"logger":"conn","msg":"Close connection","connection_id":"d150eea7-2b2a-4c6b-8b93-b2f7d8d67b9d","local_address":"$MyServerIP:10010","remote_address":"$MyPCIP:59384","purpose":"client","faked_local_addr":"$MyPublicIP:10010"}
>{"level":"debug","ts":1561734530.828584,"logger":"conn","msg":"Read from stream","connection_id":"e1486090-dd55-4bfb-834f-f33f8418a02c","local_address":"$MyServerIP:26601","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26601","bytes":0,"error":"EOF"}
>{"level":"debug","ts":1561734530.828632,"logger":"conn","msg":"Close connection","connection_id":"e1486090-dd55-4bfb-834f-f33f8418a02c","local_address":"$MyServerIP:26601","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26601"}
>{"level":"error","ts":1561734530.8287778,"logger":"main","msg":"Cannot initialize server connection","connection_id":"e1486090-dd55-4bfb-834f-f33f8418a02c","error":"Cannot handshake telegram: Cannot read RPC handshake response: Cannot read frame padding: Cannot read from socket: EOF","errorVerbose":"EOF\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/wrappers/blockcipher.go:37: Cannot read from socket\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/wrappers/mtproto_frame.go:52: Cannot read frame padding\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/telegram/middle.go:100: Cannot read RPC handshake response\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/proxy/proxy.go:118: Cannot handshake telegram"}
>{"level":"debug","ts":1561734530.828986,"logger":"conn","msg":"Close connection","connection_id":"e1486090-dd55-4bfb-834f-f33f8418a02c","local_address":"$MyServerIP:10010","remote_address":"$MyPCIP:59382","purpose":"client","faked_local_addr":"$MyPublicIP:10010"}
>{"level":"debug","ts":1561734530.8297691,"logger":"conn","msg":"Read from stream","connection_id":"b5a22f02-a7ef-4445-a078-776342de654e","local_address":"$MyServerIP:26599","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26599","bytes":0,"error":"EOF"}
>{"level":"debug","ts":1561734530.8298228,"logger":"conn","msg":"Close connection","connection_id":"b5a22f02-a7ef-4445-a078-776342de654e","local_address":"$MyServerIP:26599","remote_address":"149.154.175.50:8888","purpose":"telegram","faked_local_addr":"$MyPublicIP:26599"}
>{"level":"error","ts":1561734530.8299453,"logger":"main","msg":"Cannot initialize server connection","connection_id":"b5a22f02-a7ef-4445-a078-776342de654e","error":"Cannot handshake telegram: Cannot read RPC handshake response: Cannot read frame padding: Cannot read from socket: EOF","errorVerbose":"EOF\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/wrappers/blockcipher.go:37: Cannot read from socket\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/wrappers/mtproto_frame.go:52: Cannot read frame padding\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/telegram/middle.go:100: Cannot read RPC handshake response\n/home/vagrant/safe/go/src/github.com/9seconds/mtg/proxy/proxy.go:118: Cannot handshake telegram"}
