### ISSUE TITLE
Egress traffic and speed

### ISSUE THREAD

**Issue by L11R** [9seconds/mtg#83]
Hello. Is it okay that egress and ingress traffic and speed are almost constantly equal?
![изображение](https://user-images.githubusercontent.com/5345489/57990438-5a0a4a00-7aaf-11e9-8f8b-c3bf531b57df.png)

**Comment by 9seconds** [comment]
Hey. Yep, this is fine. This is proxy and it does not produce additional traffic :) Just as an illustration:

```
           -- ingress -->             -- egress -->
Client                       Proxy                      Telegram
           <-- egress --              <-- ingress --
```

Ingress is what proxy "ingests". Egress - what it "feeds". I know it may sound silly but treating traffic in such a way helped me with debugging a couple of times.

**Comment by L11R** [comment]
Hm. I know how proxy common works. And I got you ASCII-scheme. But maybe you should rework metrics a bit? I mean for example I am trying to download big file via Telegram:
What I am supposed to see: Few KB as requests to Telegram, and hungreds MB as downloaded data.
What I am seeing now: Some internal traffic params, those are almost constantly equal.

**Comment by 9seconds** [comment]
Makes sense
