### ISSUE TITLE
Outgoing IP address

### ISSUE THREAD

**Issue by StrangeAlex3003** [9seconds/mtg#85]
Как заставить устанавливать исходящие соединения с нужного адреса (интерфейса)?
У сервера 2 провайдера: один блокирует телеграм, второй нет. Настроен source routing.
Обычно достаточно настроить SRC ip адрес (например tcp_outgoing_adress в squid). Ни -b ни -4 не помогают, трафик всегда выходит через default gateway, с его src ip.

**Comment by 9seconds** [comment]
Исходящие - это от прокси до Телеграма? Если да, то такой возможности нет :/ -b - это касается listen socket. Могу лишь предположить, что можно попробовать запустить через докер, и уже там попытаться настроить сеть таким образом. К сожалению, у меня нет большого опыта с таким кейсом, поэтому затруднюсь предложить готовое решение
