### ISSUE TITLE
Prefer to use IPv4

### ISSUE THREAD

**Issue by pexcn** [9seconds/mtg#91]
![ipv6](https://user-images.githubusercontent.com/4590439/60889713-3d5ae900-a28c-11e9-9fca-d69ab5c24101.png)
now ipv6 first by default

**Comment by 9seconds** [comment]
Yes, please assign IPv6 IP address somewhere else or put it to another port

**Comment by pexcn** [comment]
I don't want remove my IPv6 address, what's "put it to another port" mean? now I connect my vps via IPv4 address, but from vps connect to Telegram IP was via IPv6.

**Comment by 9seconds** [comment]
I do not ask you to remove your IPv6 address, I just ask to bind proxy to another port. Let's say, you have 2 open ports, 8000 and 8001. Then bind proxy to ipv4 protocol on the port 8000 and to ipv6 on the port 8001. Please see command-line help to get an idea.

**Comment by pexcn** [comment]
ok, I will try it, thanks.

**Comment by pexcn** [comment]
Hello @9seconds :
Can you fix this? https://github.com/9seconds/mtg/commit/422ed5b0716c07c17952af5273292aa303d53ac8#commitcomment-37315999

**Comment by 9seconds** [comment]
Yes, thanks for reopening! I've seen notification but could not find it so had an impression that you've deleted it. I will do in the next week for sure

**Comment by pexcn** [comment]
Thank you, looking forward your new release. :)

**Comment by 9seconds** [comment]
Sorry for the delay. Unfortunately, I was too busy with my main work so I could not even start. I would like to tell that I do still remember about that issue and I do plan to fix it.

**Comment by pexcn** [comment]
It's okay, you may finish your work on hand first. XD
