### ISSUE TITLE
After a time just crash

### ISSUE THREAD

**Issue by hookzof** [9seconds/mtg#93]
Sorry, the log is attached as a screenshot.
System: Debian 10
![Screenshot_20190722-000104_JuiceSSH](https://user-images.githubusercontent.com/22233835/61597092-8ad44000-ac14-11e9-9773-32af436d00cb.jpg)

**Comment by 9seconds** [comment]
It is hard for me to understand the reason. As I see, it is related to the failures in linux syscalls and this is not catchable (I have a global clause to capture all errors, but it seems that this one is not a case) :/

**Comment by hookzof** [comment]
If anyone has any thoughts, write here.
