### ISSUE TITLE
Is GFW able to know the IP address of MTProxy?

### ISSUE THREAD

**Issue by JohnChu101** [9seconds/mtg#94]
When I connect to a MTProxy, is GFW able to know the IP address of my server?
If so, I doubt there's way to avoid being blocked.

**Comment by z991238** [comment]
看我上面回答。应该是特征太明显了。现在这个阶段不好用了。等TG官方出新的混淆吧

**Comment by 9seconds** [comment]
I frankly do not know. I can't check within a China
