### ISSUE TITLE
Docker one-liner bind stats port to public ip

### ISSUE THREAD

**Issue by strangecamelcaselogin** [9seconds/mtg#97]
Hello, thanks for a great job :)

As I understand, stats port should be private (default value of MTG_STATS_IP variable is 127.0.0.1).
But with docker setup, one-line example `-p 3129:3129` is equal to `-p 0.0.0.0:3129:3129`, so after executing one-liner, I got publicly available stats and links with secrets for my _not so private now_ proxy (checked by executing `curl <publicip:3129>` from my local pc).
To correct this behavior I changed `-p 3129:3129` to `-p 127.0.0.1:3129:3129`.

Should it be corrected in the docs?

**Comment by 9seconds** [comment]
I believe so, you are right, I never thought about in that way :) Could you please create PR?
