### ISSUE TITLE
Some problems with the project

### ISSUE THREAD

**Issue by z991238** [9seconds/mtg#99]
Whether this new development can be a one-click interactive script to facilitate our easy installation without understanding the code, thank you.Whether this new development can be a one-click interactive script to facilitate our easy installation without understanding the code, thank you. Because TLS tunnel is very effective under GFW in mainland China

**Comment by 9seconds** [comment]
Let's concentrate a discussion on TLS here: https://github.com/9seconds/mtg/issues/95
